; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)

define i32 @inc(i32 %x.arg) {
entry:
%x = alloca i32
  store i32 %x.arg, ptr %x
%t0 = load i32, ptr %x
%t1 = add i32 %t0, 1
  ret i32 %t1
}

define i32 @main() {
entry:
%t2 = call i32 @inc(i32 41)
  ret i32 %t2
}

