; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)

define i32 @main() {
entry:
%x = alloca i32
  store i32 40, ptr %x
%t0 = load i32, ptr %x
%t1 = add i32 %t0, 2
  store i32 %t1, ptr %x
%t2 = load i32, ptr %x
  ret i32 %t2
}

