; generated by weavec0, the Weave Stage 0 compiler

define i32 @main() {
entry:
  %i = alloca i32
  store i32 0, ptr %i
  %sum = alloca i32
  store i32 0, ptr %sum
  br label %label0
label0:
  %t0 = load i32, ptr %i
  %t1 = icmp slt i32 %t0, 7
  br i1 %t1, label %then0, label %done0
then0:
  %t2 = load i32, ptr %sum
  %t3 = add i32 %t2, 6
  store i32 %t3, ptr %sum
  %t4 = load i32, ptr %i
  %t5 = add i32 %t4, 1
  store i32 %t5, ptr %i
  br label %label0
done0:
  %t6 = load i32, ptr %sum
  ret i32 %t6
}

