; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)

@.str85 = private unnamed_addr constant [3 x i8] c"ok\00"

define i32 @sum_to(i32 %n.arg) {
entry:
  %n = alloca i32
  store i32 %n.arg, ptr %n
  %i = alloca i32
  store i32 0, ptr %i
  %acc = alloca i32
  store i32 0, ptr %acc
  br label %label0
label0:
  %t0 = load i32, ptr %i
  %t1 = load i32, ptr %n
  %t2 = icmp sle i32 %t0, %t1
  br i1 %t2, label %then0, label %done0
then0:
  %t3 = load i32, ptr %acc
  %t4 = load i32, ptr %i
  %t5 = add i32 %t3, %t4
  store i32 %t5, ptr %acc
  %t6 = load i32, ptr %i
  %t7 = add i32 %t6, 1
  store i32 %t7, ptr %i
  br label %label0
done0:
  %t8 = load i32, ptr %acc
  ret i32 %t8
}

define i32 @main() {
entry:
  %t9 = call ptr @malloc(i64 16)
  %p = alloca ptr
  store ptr %t9, ptr %p
  %t10 = load ptr, ptr %p
  %t11 = icmp eq ptr %t10, null
  br i1 %t11, label %then1, label %else1
then1:
  ret i32 1
else1:
  br label %done1
done1:
  %t12 = load ptr, ptr %p
  %t13 = getelementptr i8, ptr %t12, i64 8
  store i64 8, ptr %t13
  %t14 = load ptr, ptr %p
  %t15 = getelementptr i8, ptr %t14, i64 8
  %t16 = load i64, ptr %t15
  %stored = alloca i64
  store i64 %t16, ptr %stored
  %t17 = load ptr, ptr %p
  call void @free(ptr %t17)
  %t18 = call i32 @sum_to(i32 8)
  %n = alloca i32
  store i32 %t18, ptr %n
  %t19 = load i32, ptr %n
  %t20 = load i64, ptr %stored
  %t21 = trunc i64 %t20 to i32
  %t22 = add i32 %t19, %t21
  %t23 = sub i32 %t22, 2
  %result = alloca i32
  store i32 %t23, ptr %result
  %t24 = load i32, ptr %result
  %t25 = icmp eq i32 %t24, 42
  br i1 %t25, label %then2, label %else2
then2:
  %t26 = call i32 @puts(ptr @.str85)
  br label %done2
else2:
  br label %done2
done2:
  %t27 = load i32, ptr %result
  ret i32 %t27
}

