; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare ptr @realloc(ptr, i64)
declare ptr @memcpy(ptr, ptr, i64)
declare i64 @strlen(ptr)
declare i32 @strcmp(ptr, ptr)
declare i32 @strncmp(ptr, ptr, i64)
declare i32 @atoi(ptr)
declare i32 @putchar(i32)
declare ptr @weave_rt_read_file(ptr, ptr)
declare i32 @weave_rt_write_file(ptr, ptr, i64)
declare void @weave_rt_fatal(ptr)

define i32 @main() {
entry:
  %t0 = call i32 @putchar(i32 42)
  %_ch = alloca i32
  store i32 %t0, ptr %_ch
  ret i32 42
}

