; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)

define i32 @main() {
entry:
%a = alloca i64
  store i64 20, ptr %a
%b = alloca i64
  store i64 2, ptr %b
%t0 = load i64, ptr %b
%t1 = mul i64 %t0, 11
%c = alloca i64
  store i64 %t1, ptr %c
%t2 = load i64, ptr %a
%t3 = load i64, ptr %c
%t4 = add i64 %t2, %t3
%d = alloca i64
  store i64 %t4, ptr %d
%t5 = load i64, ptr %d
%t6 = trunc i64 %t5 to i32
  ret i32 %t6
}

