; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)

define i32 @main() {
entry:
%t0 = icmp slt i64 1, 2
  br i1 %t0, label %then0, label %else0
then0:
%t1 = icmp sle i64 2, 2
  br i1 %t1, label %then1, label %else1
then1:
%t2 = icmp ne i64 3, 4
  br i1 %t2, label %then2, label %else2
then2:
  ret i32 42
else2:
  ret i32 0
else1:
  ret i32 0
else0:
  ret i32 0
}

