; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)

define i32 @main() {
entry:
%t0 = or i1 0, 1
%t1 = and i1 1, %t0
  br i1 %t1, label %then0, label %else0
then0:
  ret i32 42
else0:
  ret i32 0
}

