; generated by weavec0, the Weave Stage 0 compiler

declare ptr @malloc(i64)
declare void @free(ptr)

define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 8)
  %p = alloca ptr
  store ptr %t0, ptr %p
  %t1 = load ptr, ptr %p
  %t2 = icmp eq ptr %t1, null
  br i1 %t2, label %then0, label %else0
then0:
  ret i32 0
else0:
  %t3 = load ptr, ptr %p
  call void @free(ptr %t3)
  ret i32 42
}

