; generated by weavec0, the Weave Stage 0 compiler

declare ptr @malloc(i64)
declare void @free(ptr)

define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 16)
  %p = alloca ptr
  store ptr %t0, ptr %p
  %t1 = load ptr, ptr %p
  %t2 = icmp eq ptr %t1, null
  br i1 %t2, label %then0, label %else0
then0:
  ret i32 0
else0:
  br label %done0
done0:
  %t3 = load ptr, ptr %p
  store i64 20, ptr %t3
  %t4 = load ptr, ptr %p
  %t5 = getelementptr i8, ptr %t4, i64 8
  store i64 22, ptr %t5
  %t6 = load ptr, ptr %p
  %t7 = load i64, ptr %t6
  %a = alloca i64
  store i64 %t7, ptr %a
  %t8 = load ptr, ptr %p
  %t9 = getelementptr i8, ptr %t8, i64 8
  %t10 = load i64, ptr %t9
  %b = alloca i64
  store i64 %t10, ptr %b
  %t11 = load ptr, ptr %p
  call void @free(ptr %t11)
  %t12 = load i64, ptr %a
  %t13 = load i64, ptr %b
  %t14 = add i64 %t12, %t13
  %t15 = trunc i64 %t14 to i32
  ret i32 %t15
}

