; generated by weavec0, the Weave Stage 0 compiler

declare ptr @malloc(i64)
declare void @free(ptr)

define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 1)
  %p = alloca ptr
  store ptr %t0, ptr %p
  %t1 = load ptr, ptr %p
  %t2 = icmp eq ptr %t1, null
  br i1 %t2, label %then0, label %else0
then0:
  ret i32 0
else0:
  br label %done0
done0:
  %t3 = load ptr, ptr %p
  store i8 42, ptr %t3
  %t4 = load ptr, ptr %p
  %t5 = load i8, ptr %t4
  %t6 = zext i8 %t5 to i32
  %x = alloca i32
  store i32 %t6, ptr %x
  %t7 = load ptr, ptr %p
  call void @free(ptr %t7)
  %t8 = load i32, ptr %x
  ret i32 %t8
}

