; generated by weavec0, the Weave Stage 0 compiler

define i32 @same_ptr(ptr %a.arg, ptr %b.arg) {
entry:
  %a = alloca ptr
  store ptr %a.arg, ptr %a
  %b = alloca ptr
  store ptr %b.arg, ptr %b
  %t0 = load ptr, ptr %a
  %t1 = load ptr, ptr %b
  %t2 = icmp eq ptr %t0, %t1
  br i1 %t2, label %then0, label %else0
then0:
  ret i32 42
else0:
  ret i32 0
}

define i32 @main() {
entry:
  %t3 = call i32 @same_ptr(ptr null, ptr null)
  ret i32 %t3
}

