; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)

define i1 @same(i1 %x.arg) {
entry:
%x = alloca i1
  store i1 %x.arg, ptr %x
%t0 = load i1, ptr %x
  ret i1 %t0
}

define i32 @main() {
entry:
%t1 = call i1 @same(i32 1)
  br i1 %t1, label %then0, label %else0
then0:
  ret i32 42
else0:
  ret i32 0
}

