; generated by weavec0, the Weave Stage 0 compiler

define i32 @add3(i32 %a.arg, i32 %b.arg, i32 %c.arg) {
entry:
  %a = alloca i32
  store i32 %a.arg, ptr %a
  %b = alloca i32
  store i32 %b.arg, ptr %b
  %c = alloca i32
  store i32 %c.arg, ptr %c
  %t0 = load i32, ptr %a
  %t1 = load i32, ptr %b
  %t2 = add i32 %t0, %t1
  %t3 = load i32, ptr %c
  %t4 = add i32 %t2, %t3
  ret i32 %t4
}

define i32 @main() {
entry:
  %t5 = call i32 @add3(i32 10, i32 20, i32 12)
  ret i32 %t5
}

