; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)

@.str2 = private unnamed_addr constant [28 x i8] c"hello from const_string_ptr\00"

define i32 @main() {
entry:
%t0 = call i32 @puts(ptr @.str2)
  ret i32 42
}

