; generated by weavec0, the Weave Stage 0 compiler

define i1 @is_answer(i32 %x.arg) {
entry:
  %x = alloca i32
  store i32 %x.arg, ptr %x
  %t0 = load i32, ptr %x
  %t1 = icmp eq i32 %t0, 42
  ret i1 %t1
}

define i32 @main() {
entry:
  %t2 = call i1 @is_answer(i32 42)
  br i1 %t2, label %then0, label %else0
then0:
  ret i32 42
else0:
  ret i32 0
}

