; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)

define i32 @main() {
entry:
%t0 = call ptr @malloc(i32 8)
%slot = alloca ptr
  store ptr %t0, ptr %slot
%t1 = load ptr, ptr %slot
%t2 = icmp eq ptr %t1, null
  br i1 %t2, label %then0, label %else0
then0:
  ret i32 0
else0:
  br label %done0
done0:
%t3 = call ptr @malloc(i32 8)
%data = alloca ptr
  store ptr %t3, ptr %data
%t4 = load ptr, ptr %data
%t5 = icmp eq ptr %t4, null
  br i1 %t5, label %then1, label %else1
then1:
%t6 = load ptr, ptr %slot
  call void @free(ptr %t6)
  ret i32 0
else1:
  br label %done1
done1:
%t7 = load ptr, ptr %slot
%t8 = load ptr, ptr %data
  store ptr %t8, ptr %t7
%t9 = load ptr, ptr %slot
%t10 = load ptr, ptr %t9
%loaded = alloca ptr
  store ptr %t10, ptr %loaded
%t11 = load ptr, ptr %loaded
  store i64 42, ptr %t11
%t12 = load ptr, ptr %data
%t13 = load i64, ptr %t12
%value = alloca i64
  store i64 %t13, ptr %value
%t14 = load ptr, ptr %data
  call void @free(ptr %t14)
%t15 = load ptr, ptr %slot
  call void @free(ptr %t15)
%t16 = load i64, ptr %value
%t17 = trunc i64 %t16 to i32
  ret i32 %t17
}

