; generated by weavec0, the Weave Stage 0 compiler

define i32 @main() {
entry:
  %x = alloca i32
  store i32 0, ptr %x
  %t0 = icmp slt i32 1, 2
  br i1 %t0, label %then0, label %else0
then0:
  store i32 42, ptr %x
  br label %done0
else0:
  store i32 0, ptr %x
  br label %done0
done0:
  %t1 = load i32, ptr %x
  ret i32 %t1
}

