; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)

@.str2 = private unnamed_addr constant [12 x i8] c"hello\0Aworld\00"

@.str8 = private unnamed_addr constant [15 x i8] c"quote: \22weave\22\00"

@.str14 = private unnamed_addr constant [13 x i8] c"backslash: \5C\00"

define i32 @main() {
entry:
  %t0 = call i32 @puts(ptr @.str2)
  %t1 = call i32 @puts(ptr @.str8)
  %t2 = call i32 @puts(ptr @.str14)
  ret i32 42
}

