; generated by weavec0, the Weave Stage 0 compiler

define i32 @main() {
entry:
  %t0 = icmp slt i32 1, 2
  %t1 = icmp sgt i32 5, 3
  %t2 = and i1 %t0, %t1
  br i1 %t2, label %then0, label %else0
then0:
  ret i32 42
else0:
  ret i32 0
}

