; generated by weavec0, the Weave Stage 0 compiler

define i32 @main() {
entry:
  %t0 = icmp slt i32 5, 2
  %t1 = icmp slt i32 6, 1
  %t2 = or i1 %t0, %t1
  %t3 = icmp slt i32 1, 99
  %t4 = or i1 %t2, %t3
  br i1 %t4, label %then0, label %else0
then0:
  ret i32 42
else0:
  ret i32 0
}

