; generated by weavec0, the Weave Stage 0 compiler

define i32 @main() {
entry:
  %t0 = icmp slt i32 7, 3
  %t1 = icmp slt i32 1, 2
  %t2 = or i1 %t0, %t1
  %t3 = icmp sgt i32 8, 4
  %t4 = and i1 %t2, %t3
  br i1 %t4, label %then0, label %else0
then0:
  ret i32 42
else0:
  ret i32 0
}

