; generated by weavec0, the Weave Stage 0 compiler

declare ptr @malloc(i64)
declare void @free(ptr)

define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 32)
  %p = alloca ptr
  store ptr %t0, ptr %p
  %t1 = load ptr, ptr %p
  %t2 = icmp eq ptr %t1, null
  br i1 %t2, label %then0, label %else0
then0:
  ret i32 0
else0:
  br label %done0
done0:
  %t3 = load ptr, ptr %p
  %t4 = getelementptr i8, ptr %t3, i64 8
  %t5 = getelementptr i8, ptr %t4, i64 8
  store i64 42, ptr %t5
  %t6 = load ptr, ptr %p
  %t7 = getelementptr i8, ptr %t6, i64 8
  %t8 = getelementptr i8, ptr %t7, i64 8
  %t9 = load i64, ptr %t8
  %v = alloca i64
  store i64 %t9, ptr %v
  %t10 = load ptr, ptr %p
  call void @free(ptr %t10)
  %t11 = load i64, ptr %v
  %t12 = trunc i64 %t11 to i32
  ret i32 %t12
}

