; generated by weavec0, the Weave Stage 0 compiler

define i32 @main() {
entry:
  %t0 = icmp sgt i32 1, 5
  br i1 %t0, label %then0, label %else0
then0:
  ret i32 1
else0:
  %t1 = icmp slt i32 2, 7
  br i1 %t1, label %then1, label %else1
then1:
  ret i32 42
else1:
  ret i32 3
}

