; generated by weavec0, the Weave Stage 0 compiler

define i32 @main() {
entry:
  %outer = alloca i32
  store i32 0, ptr %outer
  %total = alloca i32
  store i32 0, ptr %total
  br label %label0
label0:
  %t0 = load i32, ptr %outer
  %t1 = icmp slt i32 %t0, 2
  br i1 %t1, label %then0, label %done0
then0:
  %middle = alloca i32
  store i32 0, ptr %middle
  br label %label1
label1:
  %t2 = load i32, ptr %middle
  %t3 = icmp slt i32 %t2, 3
  br i1 %t3, label %then1, label %done1
then1:
  %inner = alloca i32
  store i32 0, ptr %inner
  br label %label2
label2:
  %t4 = load i32, ptr %inner
  %t5 = icmp slt i32 %t4, 7
  br i1 %t5, label %then2, label %done2
then2:
  %t6 = load i32, ptr %total
  %t7 = add i32 %t6, 1
  store i32 %t7, ptr %total
  %t8 = load i32, ptr %inner
  %t9 = add i32 %t8, 1
  store i32 %t9, ptr %inner
  br label %label2
done2:
  %t10 = load i32, ptr %middle
  %t11 = add i32 %t10, 1
  store i32 %t11, ptr %middle
  br label %label1
done1:
  %t12 = load i32, ptr %outer
  %t13 = add i32 %t12, 1
  store i32 %t13, ptr %outer
  br label %label0
done0:
  %t14 = load i32, ptr %total
  ret i32 %t14
}

