; generated by weavec0, the Weave Stage 0 compiler

define i32 @triple(i32 %x.arg) {
entry:
  %x = alloca i32
  store i32 %x.arg, ptr %x
  %t0 = load i32, ptr %x
  %t1 = load i32, ptr %x
  %t2 = add i32 %t0, %t1
  %t3 = load i32, ptr %x
  %t4 = add i32 %t2, %t3
  ret i32 %t4
}

define i32 @main() {
entry:
  %t5 = call i32 @triple(i32 14)
  ret i32 %t5
}

