; generated by weavec0, the Weave Stage 0 compiler

declare ptr @malloc(i64)
declare void @free(ptr)

define i32 @main() {
entry:
  %a = alloca i32
  store i32 10, ptr %a
  %b = alloca i64
  store i64 20, ptr %b
  %t0 = call ptr @malloc(i64 8)
  %p = alloca ptr
  store ptr %t0, ptr %p
  %t1 = load ptr, ptr %p
  %t2 = icmp eq ptr %t1, null
  br i1 %t2, label %then0, label %else0
then0:
  ret i32 0
else0:
  br label %done0
done0:
  %t3 = load ptr, ptr %p
  store i32 12, ptr %t3
  %t4 = load ptr, ptr %p
  %t5 = load i32, ptr %t4
  %c = alloca i32
  store i32 %t5, ptr %c
  %t6 = load ptr, ptr %p
  call void @free(ptr %t6)
  %t7 = load i32, ptr %a
  %t8 = load i64, ptr %b
  %t9 = trunc i64 %t8 to i32
  %t10 = add i32 %t7, %t9
  %t11 = load i32, ptr %c
  %t12 = add i32 %t10, %t11
  ret i32 %t12
}

