; generated by weavec0, the Weave Stage 0 compiler

define i32 @main() {
entry:
  %acc = alloca i32
  store i32 1, ptr %acc
  store i32 7, ptr %acc
  %t0 = load i32, ptr %acc
  %t1 = add i32 %t0, 5
  store i32 %t1, ptr %acc
  %t2 = load i32, ptr %acc
  %t3 = mul i32 %t2, 3
  store i32 %t3, ptr %acc
  %t4 = load i32, ptr %acc
  %t5 = add i32 %t4, 6
  store i32 %t5, ptr %acc
  %t6 = load i32, ptr %acc
  ret i32 %t6
}

