; generated by weavec0, the Weave Stage 0 compiler

define i32 @main() {
entry:
  %i = alloca i32
  store i32 0, ptr %i
  %total = alloca i32
  store i32 0, ptr %total
  br label %label0
label0:
  %t0 = load i32, ptr %i
  %t1 = icmp slt i32 %t0, 10
  br i1 %t1, label %then0, label %done0
then0:
  %t2 = load i32, ptr %i
  %t3 = icmp slt i32 %t2, 7
  br i1 %t3, label %then1, label %else1
then1:
  %t4 = load i32, ptr %total
  %t5 = add i32 %t4, 6
  store i32 %t5, ptr %total
  br label %done1
else1:
  %t6 = load i32, ptr %total
  %t7 = add i32 %t6, 0
  store i32 %t7, ptr %total
  br label %done1
done1:
  %t8 = load i32, ptr %i
  %t9 = add i32 %t8, 1
  store i32 %t9, ptr %i
  br label %label0
done0:
  %t10 = load i32, ptr %total
  ret i32 %t10
}

