; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)

@.str2 = private unnamed_addr constant [1 x i8] c"\00"

define i32 @main() {
entry:
  %t0 = call i32 @puts(ptr @.str2)
  ret i32 42
}

