; generated by weavec0, the Weave Stage 0 compiler

define i32 @main() {
entry:
  %i = alloca i32
  store i32 0, ptr %i
  br label %label0
label0:
  %t0 = load i32, ptr %i
  %t1 = icmp slt i32 %t0, 100
  br i1 %t1, label %then0, label %done0
then0:
  %t2 = load i32, ptr %i
  %t3 = icmp eq i32 %t2, 5
  br i1 %t3, label %then1, label %else1
then1:
  ret i32 42
else1:
  br label %done1
done1:
  %t4 = load i32, ptr %i
  %t5 = add i32 %t4, 1
  store i32 %t5, ptr %i
  br label %label0
done0:
  ret i32 0
}

