; generated by weavec0, the Weave Stage 0 compiler

define i32 @triple(i32 %x.arg) {
entry:
  %x = alloca i32
  store i32 %x.arg, ptr %x
  %t0 = load i32, ptr %x
  %t1 = mul i32 %t0, 3
  ret i32 %t1
}

define i32 @double(i32 %x.arg) {
entry:
  %x = alloca i32
  store i32 %x.arg, ptr %x
  %t2 = load i32, ptr %x
  %t3 = mul i32 %t2, 2
  ret i32 %t3
}

define i32 @main() {
entry:
  %t4 = call i32 @triple(i32 7)
  %t5 = call i32 @double(i32 %t4)
  ret i32 %t5
}

