; generated by weavec0, the Weave Stage 0 compiler

define i32 @main() {
entry:
  %a = alloca i32
  store i32 1, ptr %a
  %t0 = load i32, ptr %a
  %t1 = add i32 %t0, 1
  %b = alloca i32
  store i32 %t1, ptr %b
  %t2 = load i32, ptr %b
  %t3 = load i32, ptr %b
  %t4 = add i32 %t2, %t3
  %c = alloca i32
  store i32 %t4, ptr %c
  %t5 = load i32, ptr %c
  %t6 = load i32, ptr %c
  %t7 = add i32 %t5, %t6
  %d = alloca i32
  store i32 %t7, ptr %d
  %t8 = load i32, ptr %d
  %t9 = load i32, ptr %d
  %t10 = add i32 %t8, %t9
  %e = alloca i32
  store i32 %t10, ptr %e
  %t11 = load i32, ptr %a
  %t12 = load i32, ptr %b
  %t13 = add i32 %t11, %t12
  %t14 = load i32, ptr %c
  %t15 = add i32 %t13, %t14
  %t16 = load i32, ptr %d
  %t17 = add i32 %t15, %t16
  %t18 = load i32, ptr %e
  %t19 = add i32 %t17, %t18
  %t20 = add i32 %t19, 11
  ret i32 %t20
}

