; generated by weavec0, the Weave Stage 0 compiler

define i32 @main() {
entry:
  %t0 = sext i32 42 to i64
  %widened = alloca i64
  store i64 %t0, ptr %widened
  %t1 = load i64, ptr %widened
  %t2 = trunc i64 %t1 to i32
  ret i32 %t2
}

