; generated by weavec0, the Weave Stage 0 compiler

define i32 @main() {
entry:
  %v = alloca i32
  store i32 3, ptr %v
  %t0 = load i32, ptr %v
  %t1 = icmp eq i32 %t0, 1
  br i1 %t1, label %then0, label %else0
then0:
  ret i32 10
else0:
  %t2 = load i32, ptr %v
  %t3 = icmp eq i32 %t2, 2
  br i1 %t3, label %then1, label %else1
then1:
  ret i32 20
else1:
  %t4 = load i32, ptr %v
  %t5 = icmp eq i32 %t4, 3
  br i1 %t5, label %then2, label %else2
then2:
  ret i32 42
else2:
  ret i32 99
}

