; generated by weavec0, the Weave Stage 0 compiler

declare ptr @malloc(i64)
declare void @free(ptr)

define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 8)
  %p = alloca ptr
  store ptr %t0, ptr %p
  %t1 = load ptr, ptr %p
  %t2 = icmp eq ptr %t1, null
  br i1 %t2, label %then0, label %else0
then0:
  ret i32 0
else0:
  br label %done0
done0:
  %t3 = load ptr, ptr %p
  %t4 = getelementptr i8, ptr %t3, i64 0
  store i64 42, ptr %t4
  %t5 = load ptr, ptr %p
  %t6 = load i64, ptr %t5
  %v = alloca i64
  store i64 %t6, ptr %v
  %t7 = load ptr, ptr %p
  call void @free(ptr %t7)
  %t8 = load i64, ptr %v
  %t9 = trunc i64 %t8 to i32
  ret i32 %t9
}

