; generated by weavec0, the Weave Stage 0 compiler

define i1 @is_positive(i32 %x.arg) {
entry:
  %x = alloca i32
  store i32 %x.arg, ptr %x
  %t0 = load i32, ptr %x
  %t1 = icmp sgt i32 %t0, 0
  ret i1 %t1
}

define i32 @main() {
entry:
  %t2 = call i1 @is_positive(i32 5)
  %t3 = icmp slt i32 1, 9
  %t4 = and i1 %t2, %t3
  br i1 %t4, label %then0, label %else0
then0:
  ret i32 42
else0:
  ret i32 0
}

