; generated by weavec0, the Weave Stage 0 compiler

define i64 @shift_high(i64 %x.arg) {
entry:
  %x = alloca i64
  store i64 %x.arg, ptr %x
  %t0 = load i64, ptr %x
  %t1 = add i64 %t0, 2
  ret i64 %t1
}

define i32 @main() {
entry:
  %t2 = call i64 @shift_high(i64 40)
  %t3 = trunc i64 %t2 to i32
  ret i32 %t3
}

