; generated by weavec0, the Weave Stage 0 compiler

define i32 @main() {
entry:
  %a = alloca i32
  store i32 1, ptr %a
  %b = alloca i32
  store i32 2, ptr %b
  %c = alloca i32
  store i32 3, ptr %c
  %d = alloca i32
  store i32 4, ptr %d
  %e = alloca i32
  store i32 5, ptr %e
  %f = alloca i32
  store i32 6, ptr %f
  %g = alloca i32
  store i32 7, ptr %g
  %h = alloca i32
  store i32 8, ptr %h
  %big = alloca i64
  store i64 6, ptr %big
  %t0 = load i32, ptr %a
  %t1 = load i32, ptr %b
  %t2 = add i32 %t0, %t1
  %t3 = load i32, ptr %c
  %t4 = add i32 %t2, %t3
  %t5 = load i32, ptr %d
  %t6 = add i32 %t4, %t5
  %t7 = load i32, ptr %e
  %t8 = add i32 %t6, %t7
  %t9 = load i32, ptr %f
  %t10 = add i32 %t8, %t9
  %t11 = load i32, ptr %g
  %t12 = add i32 %t10, %t11
  %t13 = load i32, ptr %h
  %t14 = load i64, ptr %big
  %t15 = trunc i64 %t14 to i32
  %t16 = add i32 %t13, %t15
  %t17 = add i32 %t12, %t16
  ret i32 %t17
}

