; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)

define i32 @add(i32 %a.arg, i32 %b.arg) {
entry:
%a = alloca i32
  store i32 %a.arg, ptr %a
%b = alloca i32
  store i32 %b.arg, ptr %b
%t0 = load i32, ptr %a
%t1 = load i32, ptr %b
%t2 = add i32 %t0, %t1
  ret i32 %t2
}

define i32 @main() {
entry:
%t3 = call i32 @add(i32 20, i32 22)
  ret i32 %t3
}

