; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)

@.str1 = private unnamed_addr constant [17 x i8] c"hello from weave\00"

define i32 @main() {
entry:
%t0 = call i32 @puts(ptr @.str1)
  ret i32 42
}

