; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)

define i32 @main() {
entry:
%x = alloca i64
  store i64 42, ptr %x
%t0 = load i64, ptr %x
%t1 = trunc i64 %t0 to i32
  ret i32 %t1
}

