; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)

define i32 @main() {
entry:
%t0 = icmp eq ptr null, null
  br i1 %t0, label %then0, label %else0
then0:
%t1 = icmp ne ptr null, null
  br i1 %t1, label %then1, label %else1
then1:
  ret i32 0
else1:
  ret i32 42
else0:
  ret i32 0
}

