; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)

define i64 @answer64() {
entry:
  ret i64 42
}

define i32 @main() {
entry:
%t0 = call i64 @answer64()
%t1 = trunc i64 %t0 to i32
  ret i32 %t1
}

