; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)

define i32 @main() {
entry:
%t0 = call ptr @malloc(i32 24)
%buffer = alloca ptr
  store ptr %t0, ptr %buffer
%t1 = load ptr, ptr %buffer
%t2 = icmp eq ptr %t1, null
  br i1 %t2, label %then0, label %else0
then0:
  ret i32 0
else0:
  br label %done0
done0:
%t3 = call ptr @malloc(i32 8)
%data = alloca ptr
  store ptr %t3, ptr %data
%t4 = load ptr, ptr %data
%t5 = icmp eq ptr %t4, null
  br i1 %t5, label %then1, label %else1
then1:
%t6 = load ptr, ptr %buffer
  call void @free(ptr %t6)
  ret i32 0
else1:
  br label %done1
done1:
%t7 = load ptr, ptr %buffer
%t8 = load ptr, ptr %data
  store ptr %t8, ptr %t7
%t9 = load ptr, ptr %buffer
%t10 = getelementptr i8, ptr %t9, i64 8
  store i64 1, ptr %t10
%t11 = load ptr, ptr %buffer
%t12 = getelementptr i8, ptr %t11, i64 16
  store i64 8, ptr %t12
%t13 = load ptr, ptr %data
  store i8 42, ptr %t13
%t14 = load ptr, ptr %buffer
%t15 = load ptr, ptr %t14
%data2 = alloca ptr
  store ptr %t15, ptr %data2
%t16 = load ptr, ptr %data2
%t17 = load i8, ptr %t16
%t18 = zext i8 %t17 to i32
%x = alloca i32
  store i32 %t18, ptr %x
%t19 = load ptr, ptr %data
  call void @free(ptr %t19)
%t20 = load ptr, ptr %buffer
  call void @free(ptr %t20)
%t21 = load i32, ptr %x
  ret i32 %t21
}

