; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)

define i32 @main() {
entry:
%t0 = call ptr @malloc(i32 4)
%p = alloca ptr
  store ptr %t0, ptr %p
%t1 = load ptr, ptr %p
%t2 = icmp eq ptr %t1, null
  br i1 %t2, label %then0, label %else0
then0:
  ret i32 0
else0:
  br label %done0
done0:
%t3 = load ptr, ptr %p
%t4 = mul i32 21, 4
%t5 = sdiv i32 %t4, 2
  store i32 %t5, ptr %t3
%t6 = load ptr, ptr %p
%t7 = load i32, ptr %t6
%x = alloca i32
  store i32 %t7, ptr %x
%t8 = load ptr, ptr %p
  call void @free(ptr %t8)
%t9 = load i32, ptr %x
%t10 = icmp eq i32 %t9, 42
%t11 = sext i32 -1 to i64
%t12 = trunc i64 %t11 to i32
%t13 = icmp sle i32 %t12, 0
%t14 = and i1 %t10, %t13
  br i1 %t14, label %then1, label %else1
then1:
%t15 = load i32, ptr %x
  ret i32 %t15
else1:
  ret i32 0
}

