; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)

define i32 @main() {
entry:
%t0 = sub i64 50, 8
%t1 = icmp eq i64 %t0, 42
  br i1 %t1, label %then0, label %else0
then0:
  ret i32 42
else0:
  ret i32 0
}

