; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)

define i32 @main() {
entry:
%t0 = icmp eq i32 1, 2
  br i1 %t0, label %then0, label %else0
then0:
  br label %done0
else0:
  br label %done0
done0:
  ret i32 42
}

