; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)

define i32 @main() {
entry:
%i = alloca i32
  store i32 10, ptr %i
%sum = alloca i32
  store i32 42, ptr %sum
  br label %label0
label0:
%t0 = load i32, ptr %i
%t1 = icmp slt i32 %t0, 5
  br i1 %t1, label %then0, label %done0
then0:
  store i32 0, ptr %sum
%t2 = load i32, ptr %i
%t3 = add i32 %t2, 1
  store i32 %t3, ptr %i
  br label %label0
done0:
%t4 = load i32, ptr %sum
  ret i32 %t4
}

