; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)

define i32 @main() {
entry:
%t0 = call i32 @answer()
  ret i32 %t0
}

define i32 @answer() {
entry:
  ret i32 42
}

