; =============================================================================
; Weave Stage 0 Bootstrap Compiler
; 07_emit_llvm.ll
;
; Minimal LLVM IR emitter for the Stage 0 bootstrap subset.
;
; Responsibility:
;
;     AST -> LLVM IR text
;
; The emitter intentionally targets only small i32 programs. It is not an
; optimizer, verifier, type checker, or production backend.
; =============================================================================

; ----------------------------------------------------------------------------
; Emit context
; ----------------------------------------------------------------------------
;
; Stage 0 keeps the emitter state deliberately small.
;
; %weave.EmitContext = type {
;   ptr, ; source : %weave.Source*
;   ptr, ; ast    : %weave.Ast*
;   ptr, ; out    : %weave.Buffer*
;   i64, ; temp counter
;   i64, ; label counter
;   i32  ; current function return type token kind
; }

%weave.EmitContext = type { ptr, ptr, ptr, i64, i64, i32 }

; ----------------------------------------------------------------------------
; Emit context accessors
; ----------------------------------------------------------------------------

define ptr @weave_emit_source_ptr(ptr %ctx) {
entry:
  %field = getelementptr inbounds %weave.EmitContext, ptr %ctx, i32 0, i32 0
  ret ptr %field
}

define ptr @weave_emit_ast_ptr(ptr %ctx) {
entry:
  %field = getelementptr inbounds %weave.EmitContext, ptr %ctx, i32 0, i32 1
  ret ptr %field
}

define ptr @weave_emit_out_ptr(ptr %ctx) {
entry:
  %field = getelementptr inbounds %weave.EmitContext, ptr %ctx, i32 0, i32 2
  ret ptr %field
}

define ptr @weave_emit_temp_counter_ptr(ptr %ctx) {
entry:
  %field = getelementptr inbounds %weave.EmitContext, ptr %ctx, i32 0, i32 3
  ret ptr %field
}

define ptr @weave_emit_label_counter_ptr(ptr %ctx) {
entry:
  %field = getelementptr inbounds %weave.EmitContext, ptr %ctx, i32 0, i32 4
  ret ptr %field
}

define ptr @weave_emit_return_type_ptr(ptr %ctx) {
entry:
  %field = getelementptr inbounds %weave.EmitContext, ptr %ctx, i32 0, i32 5
  ret ptr %field
}

define ptr @weave_emit_source(ptr %ctx) {
entry:
  %field = call ptr @weave_emit_source_ptr(ptr %ctx)
  %value = load ptr, ptr %field
  ret ptr %value
}

define ptr @weave_emit_ast(ptr %ctx) {
entry:
  %field = call ptr @weave_emit_ast_ptr(ptr %ctx)
  %value = load ptr, ptr %field
  ret ptr %value
}

define ptr @weave_emit_out(ptr %ctx) {
entry:
  %field = call ptr @weave_emit_out_ptr(ptr %ctx)
  %value = load ptr, ptr %field
  ret ptr %value
}

define i32 @weave_emit_return_type(ptr %ctx) {
entry:
  %field = call ptr @weave_emit_return_type_ptr(ptr %ctx)
  %value = load i32, ptr %field
  ret i32 %value
}

define void @weave_emit_set_return_type(ptr %ctx, i32 %return_type) {
entry:
  %field = call ptr @weave_emit_return_type_ptr(ptr %ctx)
  store i32 %return_type, ptr %field
  ret void
}

; ----------------------------------------------------------------------------
; weave_emit_context_init
; ----------------------------------------------------------------------------

define void @weave_emit_context_init(ptr %ctx, ptr %source, ptr %ast, ptr %out) {
entry:
  %source_field = call ptr @weave_emit_source_ptr(ptr %ctx)
  %ast_field = call ptr @weave_emit_ast_ptr(ptr %ctx)
  %out_field = call ptr @weave_emit_out_ptr(ptr %ctx)
  %temp_field = call ptr @weave_emit_temp_counter_ptr(ptr %ctx)
  %label_field = call ptr @weave_emit_label_counter_ptr(ptr %ctx)
  %return_type_field = call ptr @weave_emit_return_type_ptr(ptr %ctx)

  store ptr %source, ptr %source_field
  store ptr %ast, ptr %ast_field
  store ptr %out, ptr %out_field
  store i64 0, ptr %temp_field
  store i64 0, ptr %label_field
  store i32 32, ptr %return_type_field
  ret void
}

; ----------------------------------------------------------------------------
; Text append helpers
; ----------------------------------------------------------------------------

define i32 @weave_emit_cstr(ptr %ctx, ptr %text) {
entry:
  %out = call ptr @weave_emit_out(ptr %ctx)
  %status = call i32 @weave_buffer_append_cstr(ptr %out, ptr %text)
  ret i32 %status
}

define i32 @weave_emit_byte(ptr %ctx, i32 %byte) {
entry:
  %out = call ptr @weave_emit_out(ptr %ctx)
  %status = call i32 @weave_buffer_append_byte(ptr %out, i32 %byte)
  ret i32 %status
}

define i32 @weave_emit_i32(ptr %ctx, i32 %value) {
entry:
  %out = call ptr @weave_emit_out(ptr %ctx)
  %status = call i32 @weave_buffer_append_i32(ptr %out, i32 %value)
  ret i32 %status
}

define i32 @weave_emit_newline(ptr %ctx) {
entry:
  %status = call i32 @weave_emit_byte(ptr %ctx, i32 10)
  ret i32 %status
}

; ----------------------------------------------------------------------------
; String constants used by emitter
; ----------------------------------------------------------------------------

@weave.emit.module_header = private unnamed_addr constant [126 x i8] c"; generated by weavec0, the Weave Stage 0 compiler\0A\0Adeclare i32 @puts(ptr)\0Adeclare ptr @malloc(i64)\0Adeclare void @free(ptr)\0A\0A\00"
@weave.emit.define_i32 = private unnamed_addr constant [13 x i8] c"define i32 @\00"
@weave.emit.define_i64 = private unnamed_addr constant [13 x i8] c"define i64 @\00"
@weave.emit.define_ptr = private unnamed_addr constant [13 x i8] c"define ptr @\00"
@weave.emit.define_void = private unnamed_addr constant [14 x i8] c"define void @\00"
@weave.emit.fn_sig = private unnamed_addr constant [6 x i8] c"() {\0A\00"
@weave.emit.fn_sig_1_prefix = private unnamed_addr constant [7 x i8] c"(i32 %\00"
@weave.emit.fn_sig_1_suffix = private unnamed_addr constant [9 x i8] c".arg) {\0A\00"
@weave.emit.fn_sig_2_mid = private unnamed_addr constant [12 x i8] c".arg, i32 %\00"
@weave.emit.entry = private unnamed_addr constant [8 x i8] c"entry:\0A\00"
@weave.emit.ret_i32 = private unnamed_addr constant [11 x i8] c"  ret i32 \00"
@weave.emit.ret_i64 = private unnamed_addr constant [11 x i8] c"  ret i64 \00"
@weave.emit.ret_ptr = private unnamed_addr constant [11 x i8] c"  ret ptr \00"
@weave.emit.ret_void = private unnamed_addr constant [12 x i8] c"  ret void\0A\00"
@weave.emit.close_fn = private unnamed_addr constant [4 x i8] c"}\0A\0A\00"
@weave.emit.tmp_prefix = private unnamed_addr constant [3 x i8] c"%t\00"
@weave.emit.percent = private unnamed_addr constant [2 x i8] c"%\00"
@weave.emit.arg_suffix = private unnamed_addr constant [5 x i8] c".arg\00"
@weave.emit.alloca_i32 = private unnamed_addr constant [15 x i8] c" = alloca i32\0A\00"
@weave.emit.load_i32 = private unnamed_addr constant [19 x i8] c" = load i32, ptr %\00"
@weave.emit.store_i32 = private unnamed_addr constant [13 x i8] c"  store i32 \00"
@weave.emit.alloca_i64 = private unnamed_addr constant [15 x i8] c" = alloca i64\0A\00"
@weave.emit.load_i64 = private unnamed_addr constant [19 x i8] c" = load i64, ptr %\00"
@weave.emit.load_i64_ptr = private unnamed_addr constant [18 x i8] c" = load i64, ptr \00"
@weave.emit.store_i64 = private unnamed_addr constant [13 x i8] c"  store i64 \00"
@weave.emit.load_i8_ptr = private unnamed_addr constant [17 x i8] c" = load i8, ptr \00"
@weave.emit.zext_i8 = private unnamed_addr constant [12 x i8] c" = zext i8 \00"
@weave.emit.to_i32_nl = private unnamed_addr constant [9 x i8] c" to i32\0A\00"
@weave.emit.store_i8 = private unnamed_addr constant [12 x i8] c"  store i8 \00"
@weave.emit.alloca_ptr = private unnamed_addr constant [15 x i8] c" = alloca ptr\0A\00"
@weave.emit.load_ptr = private unnamed_addr constant [19 x i8] c" = load ptr, ptr %\00"
@weave.emit.store_ptr = private unnamed_addr constant [13 x i8] c"  store ptr \00"
@weave.emit.comma_ptr_percent = private unnamed_addr constant [8 x i8] c", ptr %\00"
@weave.emit.comma_ptr = private unnamed_addr constant [7 x i8] c", ptr \00"
@weave.emit.label_prefix = private unnamed_addr constant [6 x i8] c"label\00"
@weave.emit.gep_i8 = private unnamed_addr constant [26 x i8] c" = getelementptr i8, ptr \00"
@weave.emit.add = private unnamed_addr constant [12 x i8] c" = add i32 \00"
@weave.emit.mod_i32 = private unnamed_addr constant [13 x i8] c" = srem i32 \00"
@weave.emit.add_i64 = private unnamed_addr constant [12 x i8] c" = add i64 \00"
@weave.emit.mul_i64 = private unnamed_addr constant [12 x i8] c" = mul i64 \00"
@weave.emit.icmp_lt = private unnamed_addr constant [17 x i8] c" = icmp slt i32 \00"
@weave.emit.icmp_lt_i64 = private unnamed_addr constant [17 x i8] c" = icmp slt i64 \00"
@weave.emit.icmp_le_i64 = private unnamed_addr constant [17 x i8] c" = icmp sle i64 \00"
@weave.emit.icmp_ne_i64 = private unnamed_addr constant [16 x i8] c" = icmp ne i64 \00"
@weave.emit.and_bool = private unnamed_addr constant [11 x i8] c" = and i1 \00"
@weave.emit.or_bool = private unnamed_addr constant [10 x i8] c" = or i1 \00"
@weave.emit.icmp_eq_ptr = private unnamed_addr constant [16 x i8] c" = icmp eq ptr \00"
@weave.emit.icmp_ne_ptr = private unnamed_addr constant [16 x i8] c" = icmp ne ptr \00"
@weave.emit.comma_i32 = private unnamed_addr constant [3 x i8] c", \00"
@weave.emit.comma_i64 = private unnamed_addr constant [7 x i8] c", i64 \00"
@weave.emit.null = private unnamed_addr constant [5 x i8] c"null\00"
@weave.emit.br_i1 = private unnamed_addr constant [9 x i8] c"  br i1 \00"
@weave.emit.comma_label_percent = private unnamed_addr constant [10 x i8] c", label %\00"
@weave.emit.br_label = private unnamed_addr constant [13 x i8] c"  br label %\00"
@weave.emit.then_text = private unnamed_addr constant [5 x i8] c"then\00"
@weave.emit.else_text = private unnamed_addr constant [5 x i8] c"else\00"
@weave.emit.done_text = private unnamed_addr constant [5 x i8] c"done\00"
@weave.emit.colon_nl = private unnamed_addr constant [3 x i8] c":\0A\00"
@weave.emit.space = private unnamed_addr constant [2 x i8] c" \00"
@weave.emit.call_i32 = private unnamed_addr constant [14 x i8] c" = call i32 @\00"
@weave.emit.call_i64 = private unnamed_addr constant [14 x i8] c" = call i64 @\00"
@weave.emit.call_ptr = private unnamed_addr constant [14 x i8] c" = call ptr @\00"
@weave.emit.call_void = private unnamed_addr constant [14 x i8] c"  call void @\00"
@weave.emit.call_sig_empty = private unnamed_addr constant [4 x i8] c"()\0A\00"
@weave.emit.call_sig_1 = private unnamed_addr constant [6 x i8] c"(i32 \00"
@weave.emit.call_sig_i64 = private unnamed_addr constant [6 x i8] c"(i64 \00"
@weave.emit.call_sig_ptr = private unnamed_addr constant [6 x i8] c"(ptr \00"
@weave.emit.call_sig_2_mid = private unnamed_addr constant [7 x i8] c", i32 \00"
@weave.emit.call_sig_end = private unnamed_addr constant [3 x i8] c")\0A\00"
@weave.emit.trunc_i64 = private unnamed_addr constant [14 x i8] c" = trunc i64 \00"
@weave.emit.to_i32 = private unnamed_addr constant [8 x i8] c" to i32\00"
@weave.emit.print_name = private unnamed_addr constant [6 x i8] c"print\00"
@weave.emit.str_global_prefix = private unnamed_addr constant [6 x i8] c"@.str\00"
@weave.emit.str_global_mid = private unnamed_addr constant [35 x i8] c" = private unnamed_addr constant [\00"
@weave.emit.str_type_mid = private unnamed_addr constant [10 x i8] c" x i8] c\22\00"
@weave.emit.str_suffix = private unnamed_addr constant [7 x i8] c"\\00\22\0A\0A\00"
@weave.emit.puts_call = private unnamed_addr constant [28 x i8] c" = call i32 @puts(ptr @.str\00"

; ----------------------------------------------------------------------------
; Counter helpers
; ----------------------------------------------------------------------------

define i64 @weave_emit_next_temp(ptr %ctx) {
entry:
  %field = call ptr @weave_emit_temp_counter_ptr(ptr %ctx)
  %old = load i64, ptr %field
  %next = add i64 %old, 1
  store i64 %next, ptr %field
  ret i64 %old
}

define i64 @weave_emit_next_label(ptr %ctx) {
entry:
  %field = call ptr @weave_emit_label_counter_ptr(ptr %ctx)
  %old = load i64, ptr %field
  %next = add i64 %old, 1
  store i64 %next, ptr %field
  ret i64 %old
}

; ----------------------------------------------------------------------------
; Source slice emission
; ----------------------------------------------------------------------------
;
; Append source bytes [start, start + length) to the output.
;
; Used for function names and call names. Stage 0 assumes trusted bootstrap
; source and does not yet sanitize identifiers.


define i32 @weave_emit_source_slice(ptr %ctx, i64 %start, i64 %length) {
entry:
  %source = call ptr @weave_emit_source(ptr %ctx)
  %data = call ptr @weave_source_data(ptr %source)
  %slice = getelementptr inbounds i8, ptr %data, i64 %start
  %out = call ptr @weave_emit_out(ptr %ctx)
  %status = call i32 @weave_buffer_append_bytes(ptr %out, ptr %slice, i64 %length)
  ret i32 %status
}

; ----------------------------------------------------------------------------
; Local type lookup
; ----------------------------------------------------------------------------

define i32 @weave_emit_lookup_local_type(ptr %ctx, i64 %name_start, i64 %name_len) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %count = call i64 @weave_ast_count(ptr %ast)
  br label %loop

loop:
  %i = phi i64 [0, %entry], [%next_i, %after_node]
  %found = phi i32 [32, %entry], [%found_next, %after_node]
  %done = icmp uge i64 %i, %count
  br i1 %done, label %success, label %check_node

check_node:
  %kind = call i32 @weave_ast_kind(ptr %ast, i64 %i)
  %is_let = icmp eq i32 %kind, 7
  br i1 %is_let, label %check_name, label %after_node

check_name:
  %let_name_start = call i64 @weave_ast_text_start(ptr %ast, i64 %i)
  %let_name_len = call i64 @weave_ast_text_len(ptr %ast, i64 %i)
  %source = call ptr @weave_emit_source(ptr %ctx)
  %data = call ptr @weave_source_data(ptr %source)
  %name_text = getelementptr inbounds i8, ptr %data, i64 %name_start
  %let_text = getelementptr inbounds i8, ptr %data, i64 %let_name_start
  %matches = call i32 @weave_bytes_equal(
    ptr %name_text,
    i64 %name_len,
    ptr %let_text,
    i64 %let_name_len
  )
  %is_match = icmp ne i32 %matches, 0
  br i1 %is_match, label %record, label %after_node

record:
  %let_type_wide = call i64 @weave_ast_b(ptr %ast, i64 %i)
  %let_type = trunc i64 %let_type_wide to i32
  br label %after_node

after_node:
  %found_next = phi i32 [ %found, %check_node ], [ %found, %check_name ], [ %let_type, %record ]
  %next_i = add i64 %i, 1
  br label %loop

success:
  ret i32 %found
}

; ----------------------------------------------------------------------------
; Value representation
; ----------------------------------------------------------------------------
;
; Expressions return a compact emitted-value descriptor:
;
;   >= 0 : temporary id %tN
;   <  0 : immediate i32 value encoded as -(value + 1)
;
; This lets Stage 0 avoid a richer value object while still emitting readable IR.
;
; Note: this encoding is primitive and only intended for small bootstrap tests.


define i64 @weave_emit_immediate_value(i32 %value) {
entry:
  %wide = sext i32 %value to i64
  %plus_one = add i64 %wide, 1
  %encoded = sub i64 0, %plus_one
  ret i64 %encoded
}

define i64 @weave_emit_null_value() {
entry:
  ret i64 -9223372036854775807
}

define i64 @weave_emit_void_value() {
entry:
  ret i64 -9223372036854775806
}

define i32 @weave_emitted_value_is_null(i64 %value) {
entry:
  %is_null = icmp eq i64 %value, -9223372036854775807
  br i1 %is_null, label %yes, label %no

yes:
  ret i32 1

no:
  ret i32 0
}

define i32 @weave_emitted_value_is_temp(i64 %value) {
entry:
  %is_temp = icmp sge i64 %value, 0
  br i1 %is_temp, label %yes, label %no

yes:
  ret i32 1

no:
  ret i32 0
}

define i32 @weave_emitted_value_immediate_i32(i64 %value) {
entry:
  %neg = sub i64 0, %value
  %minus_one = sub i64 %neg, 1
  %narrow = trunc i64 %minus_one to i32
  ret i32 %narrow
}

; ----------------------------------------------------------------------------
; Emit an i32 operand.
; ----------------------------------------------------------------------------
;
; Operand may be either an immediate value or a temp id.


define i32 @weave_emit_operand(ptr %ctx, i64 %value) {
entry:
  %is_null_i32 = call i32 @weave_emitted_value_is_null(i64 %value)
  %is_null = icmp ne i32 %is_null_i32, 0
  br i1 %is_null, label %null, label %check_temp

check_temp:
  %is_temp_i32 = call i32 @weave_emitted_value_is_temp(i64 %value)
  %is_temp = icmp ne i32 %is_temp_i32, 0
  br i1 %is_temp, label %temp, label %immediate

null:
  %s_null = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.null)
  %null_failed = icmp ne i32 %s_null, 0
  br i1 %null_failed, label %fail, label %success

temp:
  %s0 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.tmp_prefix)
  %temp_i32 = trunc i64 %value to i32
  %s1 = call i32 @weave_emit_i32(ptr %ctx, i32 %temp_i32)
  %s0_failed = icmp ne i32 %s0, 0
  %s1_failed = icmp ne i32 %s1, 0
  %bad0 = or i1 %s0_failed, %s1_failed
  br i1 %bad0, label %fail, label %success

immediate:
  %imm = call i32 @weave_emitted_value_immediate_i32(i64 %value)
  %s2 = call i32 @weave_emit_i32(ptr %ctx, i32 %imm)
  %bad1 = icmp ne i32 %s2, 0
  br i1 %bad1, label %fail, label %success

success:
  ret i32 0

fail:
  ret i32 1
}

; ----------------------------------------------------------------------------
; Emit an expression as an instruction operand.
; ----------------------------------------------------------------------------

define i32 @weave_emit_expr_operand(ptr %ctx, i64 %node_index) {
entry:
  %emitted = call i64 @weave_emit_expr(ptr %ctx, i64 %node_index)
  %failed = icmp eq i64 %emitted, -9223372036854775808
  br i1 %failed, label %fail, label %emit_operand

emit_operand:
  %status = call i32 @weave_emit_operand(ptr %ctx, i64 %emitted)
  %operand_failed = icmp ne i32 %status, 0
  br i1 %operand_failed, label %fail, label %success

success:
  ret i32 0

fail:
  ret i32 1
}

; ----------------------------------------------------------------------------
; Emit binary expression
; ----------------------------------------------------------------------------


define i64 @weave_emit_binary_expr(ptr %ctx, i64 %node_index) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %op_wide = call i64 @weave_ast_a(ptr %ast, i64 %node_index)
  %lhs_node = call i64 @weave_ast_b(ptr %ast, i64 %node_index)
  %rhs_node = call i64 @weave_ast_c(ptr %ast, i64 %node_index)

  %lhs_value = call i64 @weave_emit_expr(ptr %ctx, i64 %lhs_node)
  %lhs_failed = icmp eq i64 %lhs_value, -9223372036854775808
  br i1 %lhs_failed, label %fail, label %rhs

rhs:
  %rhs_value = call i64 @weave_emit_expr(ptr %ctx, i64 %rhs_node)
  %rhs_failed = icmp eq i64 %rhs_value, -9223372036854775808
  br i1 %rhs_failed, label %fail, label %emit

emit:
  %temp = call i64 @weave_emit_next_temp(ptr %ctx)
  %s0 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.tmp_prefix)
  %temp_i32 = trunc i64 %temp to i32
  %s1 = call i32 @weave_emit_i32(ptr %ctx, i32 %temp_i32)

  %op = trunc i64 %op_wide to i32
  %op_text_status = call i32 @weave_emit_binary_op_text(ptr %ctx, i32 %op)

  %s2 = call i32 @weave_emit_operand(ptr %ctx, i64 %lhs_value)

  %is_cmp_op = icmp sge i32 %op, 5
  br i1 %is_cmp_op, label %emit_cmp_rhs, label %emit_i32_rhs

emit_i32_rhs:
  %s3 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.comma_i32)
  %s4 = call i32 @weave_emit_operand(ptr %ctx, i64 %rhs_value)
  %s5 = call i32 @weave_emit_newline(ptr %ctx)
  %s3_failed = icmp ne i32 %s3, 0
  %s4_failed = icmp ne i32 %s4, 0
  %s5_failed = icmp ne i32 %s5, 0
  %i32_tail_bad0 = or i1 %s3_failed, %s4_failed
  %i32_tail_bad = or i1 %i32_tail_bad0, %s5_failed
  br label %check_status

emit_cmp_rhs:
  %s6 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.comma_i32)
  %s7 = call i32 @weave_emit_operand(ptr %ctx, i64 %rhs_value)
  %s8 = call i32 @weave_emit_newline(ptr %ctx)
  %s6_failed = icmp ne i32 %s6, 0
  %s7_failed = icmp ne i32 %s7, 0
  %s8_failed = icmp ne i32 %s8, 0
  %cmp_tail_bad0 = or i1 %s6_failed, %s7_failed
  %cmp_tail_bad = or i1 %cmp_tail_bad0, %s8_failed
  br label %check_status

check_status:
  %tail_bad = phi i1 [%i32_tail_bad, %emit_i32_rhs], [%cmp_tail_bad, %emit_cmp_rhs]
  %head_s0_failed = icmp ne i32 %s0, 0
  %head_s1_failed = icmp ne i32 %s1, 0
  %op_text_failed = icmp ne i32 %op_text_status, 0
  %s2_failed = icmp ne i32 %s2, 0
  %head_bad1 = or i1 %head_s0_failed, %head_s1_failed
  %head_bad2 = or i1 %op_text_failed, %s2_failed
  %head_bad = or i1 %head_bad1, %head_bad2
  %bad = or i1 %head_bad, %tail_bad
  br i1 %bad, label %fail, label %success

success:
  ret i64 %temp

fail:
  ret i64 -9223372036854775808
}

; ----------------------------------------------------------------------------
; weave_emit_binary_op_text
; ----------------------------------------------------------------------------

define i32 @weave_emit_binary_op_text(ptr %ctx, i32 %op) {
entry:
  %is_add = icmp eq i32 %op, 1
  br i1 %is_add, label %add, label %check_lt

check_lt:
  %is_lt = icmp eq i32 %op, 7
  br i1 %is_lt, label %lt, label %check_add_i64

add:
  %s_add = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.add)
  ret i32 %s_add

lt:
  %s_lt = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.icmp_lt)
  ret i32 %s_lt

check_add_i64:
  %is_add_i64 = icmp eq i32 %op, 11
  br i1 %is_add_i64, label %add_i64, label %check_mul_i64

check_mul_i64:
  %is_mul_i64 = icmp eq i32 %op, 12
  br i1 %is_mul_i64, label %mul_i64, label %check_lt_i64

check_lt_i64:
  %is_lt_i64 = icmp eq i32 %op, 13
  br i1 %is_lt_i64, label %lt_i64, label %check_le_i64

check_le_i64:
  %is_le_i64 = icmp eq i32 %op, 14
  br i1 %is_le_i64, label %le_i64, label %check_ne_i64

check_ne_i64:
  %is_ne_i64 = icmp eq i32 %op, 15
  br i1 %is_ne_i64, label %ne_i64, label %check_and_bool

check_and_bool:
  %is_and_bool = icmp eq i32 %op, 16
  br i1 %is_and_bool, label %and_bool, label %check_or_bool

check_or_bool:
  %is_or_bool = icmp eq i32 %op, 17
  br i1 %is_or_bool, label %or_bool, label %check_eq_ptr

check_eq_ptr:
  %is_eq_ptr = icmp eq i32 %op, 18
  br i1 %is_eq_ptr, label %eq_ptr, label %check_ne_ptr

check_ne_ptr:
  %is_ne_ptr = icmp eq i32 %op, 19
  br i1 %is_ne_ptr, label %ne_ptr, label %check_mod_i32

check_mod_i32:
  %is_mod_i32 = icmp eq i32 %op, 20
  br i1 %is_mod_i32, label %mod_i32, label %fail

add_i64:
  %s_add_i64 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.add_i64)
  ret i32 %s_add_i64

mul_i64:
  %s_mul_i64 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.mul_i64)
  ret i32 %s_mul_i64

lt_i64:
  %s_lt_i64 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.icmp_lt_i64)
  ret i32 %s_lt_i64

le_i64:
  %s_le_i64 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.icmp_le_i64)
  ret i32 %s_le_i64

ne_i64:
  %s_ne_i64 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.icmp_ne_i64)
  ret i32 %s_ne_i64

and_bool:
  %s_and_bool = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.and_bool)
  ret i32 %s_and_bool

or_bool:
  %s_or_bool = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.or_bool)
  ret i32 %s_or_bool

eq_ptr:
  %s_eq_ptr = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.icmp_eq_ptr)
  ret i32 %s_eq_ptr

ne_ptr:
  %s_ne_ptr = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.icmp_ne_ptr)
  ret i32 %s_ne_ptr

mod_i32:
  %s_mod_i32 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.mod_i32)
  ret i32 %s_mod_i32

fail:
  ret i32 1
}

; ----------------------------------------------------------------------------
; weave_emit_string_global
; ----------------------------------------------------------------------------

define i32 @weave_emit_string_global(ptr %ctx, i64 %node_index) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %text_start = call i64 @weave_ast_text_start(ptr %ast, i64 %node_index)
  %text_len = call i64 @weave_ast_text_len(ptr %ast, i64 %node_index)
  %type_len = add i64 %text_len, 1

  %s0 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.str_global_prefix)
  %node_i32 = trunc i64 %node_index to i32
  %s1 = call i32 @weave_emit_i32(ptr %ctx, i32 %node_i32)
  %s2 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.str_global_mid)
  %type_len_i32 = trunc i64 %type_len to i32
  %s3 = call i32 @weave_emit_i32(ptr %ctx, i32 %type_len_i32)
  %s4 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.str_type_mid)
  %s5 = call i32 @weave_emit_source_slice(ptr %ctx, i64 %text_start, i64 %text_len)
  %s6 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.str_suffix)

  %s0_failed = icmp ne i32 %s0, 0
  %s1_failed = icmp ne i32 %s1, 0
  %s2_failed = icmp ne i32 %s2, 0
  %s3_failed = icmp ne i32 %s3, 0
  %s4_failed = icmp ne i32 %s4, 0
  %s5_failed = icmp ne i32 %s5, 0
  %s6_failed = icmp ne i32 %s6, 0
  %bad01 = or i1 %s0_failed, %s1_failed
  %bad23 = or i1 %s2_failed, %s3_failed
  %bad45 = or i1 %s4_failed, %s5_failed
  %bad0123 = or i1 %bad01, %bad23
  %bad012345 = or i1 %bad0123, %bad45
  %bad = or i1 %bad012345, %s6_failed
  br i1 %bad, label %fail, label %success

success:
  ret i32 0

fail:
  ret i32 1
}

; ----------------------------------------------------------------------------
; weave_emit_string_globals
; ----------------------------------------------------------------------------

define i32 @weave_emit_string_globals(ptr %ctx) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %node_count = call i64 @weave_ast_count(ptr %ast)
  br label %loop

loop:
  %i = phi i64 [0, %entry], [%next_i, %after_node]
  %done = icmp uge i64 %i, %node_count
  br i1 %done, label %success, label %check_node

check_node:
  %kind = call i32 @weave_ast_kind(ptr %ast, i64 %i)
  %is_string = icmp eq i32 %kind, 12
  br i1 %is_string, label %emit_string, label %after_node

emit_string:
  %status = call i32 @weave_emit_string_global(ptr %ctx, i64 %i)
  %failed = icmp ne i32 %status, 0
  br i1 %failed, label %fail, label %after_node

after_node:
  %next_i = add i64 %i, 1
  br label %loop

success:
  ret i32 0

fail:
  ret i32 1
}

; ----------------------------------------------------------------------------
; weave_emit_name_expr
; ----------------------------------------------------------------------------

define i64 @weave_emit_name_expr(ptr %ctx, i64 %node_index) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %name_start = call i64 @weave_ast_text_start(ptr %ast, i64 %node_index)
  %name_len = call i64 @weave_ast_text_len(ptr %ast, i64 %node_index)
  %temp = call i64 @weave_emit_next_temp(ptr %ctx)
  %type_kind = call i32 @weave_emit_lookup_local_type(ptr %ctx, i64 %name_start, i64 %name_len)
  %is_ptr = icmp eq i32 %type_kind, 58

  %s0 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.tmp_prefix)
  %temp_i32 = trunc i64 %temp to i32
  %s1 = call i32 @weave_emit_i32(ptr %ctx, i32 %temp_i32)
  br i1 %is_ptr, label %emit_ptr, label %check_i64

check_i64:
  %is_i64 = icmp eq i32 %type_kind, 39
  br i1 %is_i64, label %emit_i64, label %emit_i32

emit_i32:
  %s2_i32 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.load_i32)
  %s3_i32 = call i32 @weave_emit_source_slice(ptr %ctx, i64 %name_start, i64 %name_len)
  %s4_i32 = call i32 @weave_emit_newline(ptr %ctx)
  %s0_failed = icmp ne i32 %s0, 0
  %s1_failed = icmp ne i32 %s1, 0
  %s2_failed = icmp ne i32 %s2_i32, 0
  %s3_failed = icmp ne i32 %s3_i32, 0
  %s4_failed = icmp ne i32 %s4_i32, 0
  %bad01 = or i1 %s0_failed, %s1_failed
  %bad23 = or i1 %s2_failed, %s3_failed
  %bad0123 = or i1 %bad01, %bad23
  %bad = or i1 %bad0123, %s4_failed
  br i1 %bad, label %fail, label %success

emit_i64:
  %s2_i64 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.load_i64)
  %s3_i64 = call i32 @weave_emit_source_slice(ptr %ctx, i64 %name_start, i64 %name_len)
  %s4_i64 = call i32 @weave_emit_newline(ptr %ctx)
  %t0_failed = icmp ne i32 %s0, 0
  %t1_failed = icmp ne i32 %s1, 0
  %t2_failed = icmp ne i32 %s2_i64, 0
  %t3_failed = icmp ne i32 %s3_i64, 0
  %t4_failed = icmp ne i32 %s4_i64, 0
  %tb01 = or i1 %t0_failed, %t1_failed
  %tb23 = or i1 %t2_failed, %t3_failed
  %tb0123 = or i1 %tb01, %tb23
  %tb = or i1 %tb0123, %t4_failed
  br i1 %tb, label %fail, label %success

emit_ptr:
  %s2_ptr = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.load_ptr)
  %s3_ptr = call i32 @weave_emit_source_slice(ptr %ctx, i64 %name_start, i64 %name_len)
  %s4_ptr = call i32 @weave_emit_newline(ptr %ctx)
  %p0_failed = icmp ne i32 %s0, 0
  %p1_failed = icmp ne i32 %s1, 0
  %p2_failed = icmp ne i32 %s2_ptr, 0
  %p3_failed = icmp ne i32 %s3_ptr, 0
  %p4_failed = icmp ne i32 %s4_ptr, 0
  %pb01 = or i1 %p0_failed, %p1_failed
  %pb23 = or i1 %p2_failed, %p3_failed
  %pb0123 = or i1 %pb01, %pb23
  %pb = or i1 %pb0123, %p4_failed
  br i1 %pb, label %fail, label %success

success:
  ret i64 %temp

fail:
  ret i64 -9223372036854775808
}

; ----------------------------------------------------------------------------
; weave_emit_expr
; ----------------------------------------------------------------------------
;
; Returns emitted-value descriptor or INT64_MIN on failure.


define i64 @weave_emit_expr(ptr %ctx, i64 %node_index) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %kind = call i32 @weave_ast_kind(ptr %ast, i64 %node_index)

  %is_int = icmp eq i32 %kind, 11
  br i1 %is_int, label %integer, label %check_binary

check_binary:
  %is_binary = icmp eq i32 %kind, 10
  br i1 %is_binary, label %binary, label %check_cast

check_call:
  %is_call = icmp eq i32 %kind, 9
  br i1 %is_call, label %call, label %check_name

check_cast:
  %is_cast = icmp eq i32 %kind, 15
  br i1 %is_cast, label %cast, label %check_call

check_name:
  %is_name = icmp eq i32 %kind, 13
  br i1 %is_name, label %name, label %check_null

check_null:
  %is_null = icmp eq i32 %kind, 16
  br i1 %is_null, label %null, label %check_call_ptr

check_call_ptr:
  %is_call_ptr = icmp eq i32 %kind, 18
  br i1 %is_call_ptr, label %call_ptr, label %check_call_void

check_call_void:
  %is_call_void = icmp eq i32 %kind, 19
  br i1 %is_call_void, label %call_void, label %check_ptr_add

check_ptr_add:
  %is_ptr_add = icmp eq i32 %kind, 21
  br i1 %is_ptr_add, label %ptr_add, label %check_load_i64

check_load_i64:
  %is_load_i64 = icmp eq i32 %kind, 22
  br i1 %is_load_i64, label %load_i64, label %check_load_u8

check_load_u8:
  %is_load_u8 = icmp eq i32 %kind, 24
  br i1 %is_load_u8, label %load_u8, label %check_call_i64

check_call_i64:
  %is_call_i64 = icmp eq i32 %kind, 26
  br i1 %is_call_i64, label %call_i64, label %unsupported

integer:
  %value_wide = call i64 @weave_ast_a(ptr %ast, i64 %node_index)
  %value = trunc i64 %value_wide to i32
  %encoded = call i64 @weave_emit_immediate_value(i32 %value)
  ret i64 %encoded

binary:
  %binary_value = call i64 @weave_emit_binary_expr(ptr %ctx, i64 %node_index)
  ret i64 %binary_value

call:
  %call_value = call i64 @weave_emit_call_expr(ptr %ctx, i64 %node_index)
  ret i64 %call_value

cast:
  %cast_value = call i64 @weave_emit_cast_expr(ptr %ctx, i64 %node_index)
  ret i64 %cast_value

name:
  %name_value = call i64 @weave_emit_name_expr(ptr %ctx, i64 %node_index)
  ret i64 %name_value

null:
  %null_value = call i64 @weave_emit_null_value()
  ret i64 %null_value

call_ptr:
  %call_ptr_value = call i64 @weave_emit_call_ptr_expr(ptr %ctx, i64 %node_index)
  ret i64 %call_ptr_value

call_void:
  %call_void_value = call i64 @weave_emit_call_void_expr(ptr %ctx, i64 %node_index)
  ret i64 %call_void_value

ptr_add:
  %ptr_add_value = call i64 @weave_emit_ptr_add_expr(ptr %ctx, i64 %node_index)
  ret i64 %ptr_add_value

load_i64:
  %load_i64_value = call i64 @weave_emit_load_i64_expr(ptr %ctx, i64 %node_index)
  ret i64 %load_i64_value

load_u8:
  %load_u8_value = call i64 @weave_emit_load_u8_expr(ptr %ctx, i64 %node_index)
  ret i64 %load_u8_value

call_i64:
  %call_i64_value = call i64 @weave_emit_call_i64_expr(ptr %ctx, i64 %node_index)
  ret i64 %call_i64_value

unsupported:
  ret i64 -9223372036854775808
}

; ----------------------------------------------------------------------------
; weave_emit_call_expr
; ----------------------------------------------------------------------------
;
; Stage 0 supports one or two i32 arguments.


define i64 @weave_emit_call_expr(ptr %ctx, i64 %node_index) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %arg_node = call i64 @weave_ast_a(ptr %ast, i64 %node_index)
  %arg2_node = call i64 @weave_ast_b(ptr %ast, i64 %node_index)
  %arg_count = call i64 @weave_ast_c(ptr %ast, i64 %node_index)
  %name_start = call i64 @weave_ast_text_start(ptr %ast, i64 %node_index)
  %name_len = call i64 @weave_ast_text_len(ptr %ast, i64 %node_index)
  %source = call ptr @weave_emit_source(ptr %ctx)
  %source_data = call ptr @weave_source_data(ptr %source)
  %name_text = getelementptr inbounds i8, ptr %source_data, i64 %name_start
  %is_print_i32 = call i32 @weave_bytes_equal(ptr %name_text, i64 %name_len, ptr @weave.emit.print_name, i64 5)
  %is_print = icmp ne i32 %is_print_i32, 0
  br i1 %is_print, label %print_call, label %normal_call

print_call:
  %print_arg_kind = call i32 @weave_ast_kind(ptr %ast, i64 %arg_node)
  %print_arg_is_string = icmp eq i32 %print_arg_kind, 12
  br i1 %print_arg_is_string, label %emit_print, label %fail

emit_print:
  %print_temp = call i64 @weave_emit_next_temp(ptr %ctx)
  %p0 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.tmp_prefix)
  %print_temp_i32 = trunc i64 %print_temp to i32
  %p1 = call i32 @weave_emit_i32(ptr %ctx, i32 %print_temp_i32)
  %p2 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.puts_call)
  %arg_i32 = trunc i64 %arg_node to i32
  %p3 = call i32 @weave_emit_i32(ptr %ctx, i32 %arg_i32)
  %p4 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.call_sig_end)
  %p0_failed = icmp ne i32 %p0, 0
  %p1_failed = icmp ne i32 %p1, 0
  %p2_failed = icmp ne i32 %p2, 0
  %p3_failed = icmp ne i32 %p3, 0
  %p4_failed = icmp ne i32 %p4, 0
  %p_bad01 = or i1 %p0_failed, %p1_failed
  %p_bad23 = or i1 %p2_failed, %p3_failed
  %p_bad0123 = or i1 %p_bad01, %p_bad23
  %p_bad = or i1 %p_bad0123, %p4_failed
  br i1 %p_bad, label %fail, label %print_success

print_success:
  ret i64 %print_temp

normal_call:
  %arg_value = call i64 @weave_emit_expr(ptr %ctx, i64 %arg_node)
  %arg_failed = icmp eq i64 %arg_value, -9223372036854775808
  br i1 %arg_failed, label %fail, label %maybe_arg2

maybe_arg2:
  %has_arg2 = icmp eq i64 %arg_count, 2
  br i1 %has_arg2, label %emit_arg2_value, label %emit

emit_arg2_value:
  %arg2_value = call i64 @weave_emit_expr(ptr %ctx, i64 %arg2_node)
  %arg2_failed = icmp eq i64 %arg2_value, -9223372036854775808
  br i1 %arg2_failed, label %fail, label %emit

emit:
  %arg2_value_for_call = phi i64 [0, %maybe_arg2], [%arg2_value, %emit_arg2_value]
  br label %emit_call

emit_call:
  %temp = call i64 @weave_emit_next_temp(ptr %ctx)
  %s0 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.tmp_prefix)
  %temp_i32 = trunc i64 %temp to i32
  %s1 = call i32 @weave_emit_i32(ptr %ctx, i32 %temp_i32)
  %s2 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.call_i32)
  %s3 = call i32 @weave_emit_source_slice(ptr %ctx, i64 %name_start, i64 %name_len)
  %s4 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.call_sig_1)
  %s5 = call i32 @weave_emit_operand(ptr %ctx, i64 %arg_value)
  br i1 %has_arg2, label %emit_arg2_text, label %emit_call_end

emit_arg2_text:
  %s6_arg2_a = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.call_sig_2_mid)
  %s6_arg2_b = call i32 @weave_emit_operand(ptr %ctx, i64 %arg2_value_for_call)
  %s6_arg2_a_failed = icmp ne i32 %s6_arg2_a, 0
  %s6_arg2_b_failed = icmp ne i32 %s6_arg2_b, 0
  %s6_arg2_failed = or i1 %s6_arg2_a_failed, %s6_arg2_b_failed
  br label %emit_call_end

emit_call_end:
  %s6_arg2_status = phi i1 [false, %emit_call], [%s6_arg2_failed, %emit_arg2_text]
  %s6 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.call_sig_end)

  %s0_failed = icmp ne i32 %s0, 0
  %s1_failed = icmp ne i32 %s1, 0
  %s2_failed = icmp ne i32 %s2, 0
  %s3_failed = icmp ne i32 %s3, 0
  %s4_failed = icmp ne i32 %s4, 0
  %s5_failed = icmp ne i32 %s5, 0
  %b0 = or i1 %s0_failed, %s1_failed
  %b1 = or i1 %s2_failed, %s3_failed
  %b2 = or i1 %s4_failed, %s5_failed
  %b3 = icmp ne i32 %s6, 0
  %bad01 = or i1 %b0, %b1
  %bad23 = or i1 %b2, %b3
  %bad0123 = or i1 %bad01, %bad23
  %bad = or i1 %bad0123, %s6_arg2_status
  br i1 %bad, label %fail, label %success

success:
  ret i64 %temp

fail:
  ret i64 -9223372036854775808
}

; ----------------------------------------------------------------------------
; weave_emit_ptr_add_expr
; ----------------------------------------------------------------------------

define i64 @weave_emit_ptr_add_expr(ptr %ctx, i64 %node_index) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %base_node = call i64 @weave_ast_a(ptr %ast, i64 %node_index)
  %offset_node = call i64 @weave_ast_b(ptr %ast, i64 %node_index)
  %base_value = call i64 @weave_emit_expr(ptr %ctx, i64 %base_node)
  %base_failed = icmp eq i64 %base_value, -9223372036854775808
  br i1 %base_failed, label %fail, label %offset

offset:
  %offset_value = call i64 @weave_emit_expr(ptr %ctx, i64 %offset_node)
  %offset_failed = icmp eq i64 %offset_value, -9223372036854775808
  br i1 %offset_failed, label %fail, label %emit

emit:
  %temp = call i64 @weave_emit_next_temp(ptr %ctx)
  %s0 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.tmp_prefix)
  %temp_i32 = trunc i64 %temp to i32
  %s1 = call i32 @weave_emit_i32(ptr %ctx, i32 %temp_i32)
  %s2 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.gep_i8)
  %s3 = call i32 @weave_emit_operand(ptr %ctx, i64 %base_value)
  %s4 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.comma_i64)
  %s5 = call i32 @weave_emit_operand(ptr %ctx, i64 %offset_value)
  %s6 = call i32 @weave_emit_newline(ptr %ctx)
  %s0_failed = icmp ne i32 %s0, 0
  %s1_failed = icmp ne i32 %s1, 0
  %s2_failed = icmp ne i32 %s2, 0
  %s3_failed = icmp ne i32 %s3, 0
  %s4_failed = icmp ne i32 %s4, 0
  %s5_failed = icmp ne i32 %s5, 0
  %s6_failed = icmp ne i32 %s6, 0
  %bad01 = or i1 %s0_failed, %s1_failed
  %bad23 = or i1 %s2_failed, %s3_failed
  %bad45 = or i1 %s4_failed, %s5_failed
  %bad0123 = or i1 %bad01, %bad23
  %bad012345 = or i1 %bad0123, %bad45
  %bad = or i1 %bad012345, %s6_failed
  br i1 %bad, label %fail, label %success

success:
  ret i64 %temp

fail:
  ret i64 -9223372036854775808
}

; ----------------------------------------------------------------------------
; weave_emit_load_i64_expr
; ----------------------------------------------------------------------------

define i64 @weave_emit_load_i64_expr(ptr %ctx, i64 %node_index) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %ptr_node = call i64 @weave_ast_a(ptr %ast, i64 %node_index)
  %ptr_value = call i64 @weave_emit_expr(ptr %ctx, i64 %ptr_node)
  %ptr_failed = icmp eq i64 %ptr_value, -9223372036854775808
  br i1 %ptr_failed, label %fail, label %emit

emit:
  %temp = call i64 @weave_emit_next_temp(ptr %ctx)
  %s0 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.tmp_prefix)
  %temp_i32 = trunc i64 %temp to i32
  %s1 = call i32 @weave_emit_i32(ptr %ctx, i32 %temp_i32)
  %s2 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.load_i64_ptr)
  %s3 = call i32 @weave_emit_operand(ptr %ctx, i64 %ptr_value)
  %s4 = call i32 @weave_emit_newline(ptr %ctx)
  %s0_failed = icmp ne i32 %s0, 0
  %s1_failed = icmp ne i32 %s1, 0
  %s2_failed = icmp ne i32 %s2, 0
  %s3_failed = icmp ne i32 %s3, 0
  %s4_failed = icmp ne i32 %s4, 0
  %bad01 = or i1 %s0_failed, %s1_failed
  %bad23 = or i1 %s2_failed, %s3_failed
  %bad0123 = or i1 %bad01, %bad23
  %bad = or i1 %bad0123, %s4_failed
  br i1 %bad, label %fail, label %success

success:
  ret i64 %temp

fail:
  ret i64 -9223372036854775808
}

; ----------------------------------------------------------------------------
; weave_emit_load_u8_expr
; ----------------------------------------------------------------------------

define i64 @weave_emit_load_u8_expr(ptr %ctx, i64 %node_index) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %ptr_node = call i64 @weave_ast_a(ptr %ast, i64 %node_index)
  %ptr_value = call i64 @weave_emit_expr(ptr %ctx, i64 %ptr_node)
  %ptr_failed = icmp eq i64 %ptr_value, -9223372036854775808
  br i1 %ptr_failed, label %fail, label %emit_load

emit_load:
  %load_temp = call i64 @weave_emit_next_temp(ptr %ctx)
  %l0 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.tmp_prefix)
  %load_temp_i32 = trunc i64 %load_temp to i32
  %l1 = call i32 @weave_emit_i32(ptr %ctx, i32 %load_temp_i32)
  %l2 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.load_i8_ptr)
  %l3 = call i32 @weave_emit_operand(ptr %ctx, i64 %ptr_value)
  %l4 = call i32 @weave_emit_newline(ptr %ctx)
  %l0_failed = icmp ne i32 %l0, 0
  %l1_failed = icmp ne i32 %l1, 0
  %l2_failed = icmp ne i32 %l2, 0
  %l3_failed = icmp ne i32 %l3, 0
  %l4_failed = icmp ne i32 %l4, 0
  %load_bad01 = or i1 %l0_failed, %l1_failed
  %load_bad23 = or i1 %l2_failed, %l3_failed
  %load_bad0123 = or i1 %load_bad01, %load_bad23
  %load_bad = or i1 %load_bad0123, %l4_failed
  br i1 %load_bad, label %fail, label %emit_zext

emit_zext:
  %zext_temp = call i64 @weave_emit_next_temp(ptr %ctx)
  %z0 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.tmp_prefix)
  %zext_temp_i32 = trunc i64 %zext_temp to i32
  %z1 = call i32 @weave_emit_i32(ptr %ctx, i32 %zext_temp_i32)
  %z2 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.zext_i8)
  %z3 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.tmp_prefix)
  %z4 = call i32 @weave_emit_i32(ptr %ctx, i32 %load_temp_i32)
  %z5 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.to_i32_nl)
  %z0_failed = icmp ne i32 %z0, 0
  %z1_failed = icmp ne i32 %z1, 0
  %z2_failed = icmp ne i32 %z2, 0
  %z3_failed = icmp ne i32 %z3, 0
  %z4_failed = icmp ne i32 %z4, 0
  %z5_failed = icmp ne i32 %z5, 0
  %z_bad01 = or i1 %z0_failed, %z1_failed
  %z_bad23 = or i1 %z2_failed, %z3_failed
  %z_bad45 = or i1 %z4_failed, %z5_failed
  %z_bad0123 = or i1 %z_bad01, %z_bad23
  %z_bad = or i1 %z_bad0123, %z_bad45
  br i1 %z_bad, label %fail, label %success

success:
  ret i64 %zext_temp

fail:
  ret i64 -9223372036854775808
}

; ----------------------------------------------------------------------------
; weave_emit_call_i64_expr
; ----------------------------------------------------------------------------

define i64 @weave_emit_call_i64_expr(ptr %ctx, i64 %node_index) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %name_start = call i64 @weave_ast_text_start(ptr %ast, i64 %node_index)
  %name_len = call i64 @weave_ast_text_len(ptr %ast, i64 %node_index)
  %temp = call i64 @weave_emit_next_temp(ptr %ctx)
  %s0 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.tmp_prefix)
  %temp_i32 = trunc i64 %temp to i32
  %s1 = call i32 @weave_emit_i32(ptr %ctx, i32 %temp_i32)
  %s2 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.call_i64)
  %s3 = call i32 @weave_emit_source_slice(ptr %ctx, i64 %name_start, i64 %name_len)
  %s4 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.call_sig_empty)
  %s0_failed = icmp ne i32 %s0, 0
  %s1_failed = icmp ne i32 %s1, 0
  %s2_failed = icmp ne i32 %s2, 0
  %s3_failed = icmp ne i32 %s3, 0
  %s4_failed = icmp ne i32 %s4, 0
  %bad01 = or i1 %s0_failed, %s1_failed
  %bad23 = or i1 %s2_failed, %s3_failed
  %bad0123 = or i1 %bad01, %bad23
  %bad = or i1 %bad0123, %s4_failed
  br i1 %bad, label %fail, label %success

success:
  ret i64 %temp

fail:
  ret i64 -9223372036854775808
}

; ----------------------------------------------------------------------------
; weave_emit_call_ptr_expr
; ----------------------------------------------------------------------------
;
; Stage 0 admits malloc-shaped pointer calls: (call_ptr name i64-arg).

define i64 @weave_emit_call_ptr_expr(ptr %ctx, i64 %node_index) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %arg_node = call i64 @weave_ast_a(ptr %ast, i64 %node_index)
  %arg_count = call i64 @weave_ast_c(ptr %ast, i64 %node_index)
  %name_start = call i64 @weave_ast_text_start(ptr %ast, i64 %node_index)
  %name_len = call i64 @weave_ast_text_len(ptr %ast, i64 %node_index)
  %has_arg = icmp ne i64 %arg_count, 0
  br i1 %has_arg, label %eval_arg, label %emit

eval_arg:
  %arg_value = call i64 @weave_emit_expr(ptr %ctx, i64 %arg_node)
  %arg_failed = icmp eq i64 %arg_value, -9223372036854775808
  br i1 %arg_failed, label %fail, label %emit

emit:
  %arg_value_for_call = phi i64 [0, %entry], [%arg_value, %eval_arg]
  %temp = call i64 @weave_emit_next_temp(ptr %ctx)
  %s0 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.tmp_prefix)
  %temp_i32 = trunc i64 %temp to i32
  %s1 = call i32 @weave_emit_i32(ptr %ctx, i32 %temp_i32)
  %s2 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.call_ptr)
  %s3 = call i32 @weave_emit_source_slice(ptr %ctx, i64 %name_start, i64 %name_len)
  br i1 %has_arg, label %emit_arg_sig, label %emit_empty_sig

emit_arg_sig:
  %s4 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.call_sig_i64)
  %s5 = call i32 @weave_emit_operand(ptr %ctx, i64 %arg_value_for_call)
  %s6 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.call_sig_end)
  %s4_arg_failed = icmp ne i32 %s4, 0
  %s5_arg_failed = icmp ne i32 %s5, 0
  %s6_arg_failed = icmp ne i32 %s6, 0
  %arg_bad01 = or i1 %s4_arg_failed, %s5_arg_failed
  %arg_bad = or i1 %arg_bad01, %s6_arg_failed
  br label %check_status

emit_empty_sig:
  %s4_empty = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.call_sig_empty)
  %empty_bad = icmp ne i32 %s4_empty, 0
  br label %check_status

check_status:
  %tail_bad = phi i1 [%arg_bad, %emit_arg_sig], [%empty_bad, %emit_empty_sig]
  %s0_failed = icmp ne i32 %s0, 0
  %s1_failed = icmp ne i32 %s1, 0
  %s2_failed = icmp ne i32 %s2, 0
  %s3_failed = icmp ne i32 %s3, 0
  %bad01 = or i1 %s0_failed, %s1_failed
  %bad23 = or i1 %s2_failed, %s3_failed
  %bad0123 = or i1 %bad01, %bad23
  %bad = or i1 %bad0123, %tail_bad
  br i1 %bad, label %fail, label %success

success:
  ret i64 %temp

fail:
  ret i64 -9223372036854775808
}

; ----------------------------------------------------------------------------
; weave_emit_call_void_expr
; ----------------------------------------------------------------------------
;
; Stage 0 admits free-shaped void calls: (call_void name ptr-arg).

define i64 @weave_emit_call_void_expr(ptr %ctx, i64 %node_index) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %arg_node = call i64 @weave_ast_a(ptr %ast, i64 %node_index)
  %arg_count = call i64 @weave_ast_c(ptr %ast, i64 %node_index)
  %name_start = call i64 @weave_ast_text_start(ptr %ast, i64 %node_index)
  %name_len = call i64 @weave_ast_text_len(ptr %ast, i64 %node_index)
  %has_arg = icmp ne i64 %arg_count, 0
  br i1 %has_arg, label %eval_arg, label %emit

eval_arg:
  %arg_value = call i64 @weave_emit_expr(ptr %ctx, i64 %arg_node)
  %arg_failed = icmp eq i64 %arg_value, -9223372036854775808
  br i1 %arg_failed, label %fail, label %emit

emit:
  %arg_value_for_call = phi i64 [0, %entry], [%arg_value, %eval_arg]
  %s0 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.call_void)
  %s1 = call i32 @weave_emit_source_slice(ptr %ctx, i64 %name_start, i64 %name_len)
  br i1 %has_arg, label %emit_arg_sig, label %emit_empty_sig

emit_arg_sig:
  %s2 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.call_sig_ptr)
  %s3 = call i32 @weave_emit_operand(ptr %ctx, i64 %arg_value_for_call)
  %s4 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.call_sig_end)
  %s2_arg_failed = icmp ne i32 %s2, 0
  %s3_arg_failed = icmp ne i32 %s3, 0
  %s4_arg_failed = icmp ne i32 %s4, 0
  %arg_bad01 = or i1 %s2_arg_failed, %s3_arg_failed
  %arg_bad = or i1 %arg_bad01, %s4_arg_failed
  br label %check_status

emit_empty_sig:
  %s2_empty = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.call_sig_empty)
  %empty_bad = icmp ne i32 %s2_empty, 0
  br label %check_status

check_status:
  %tail_bad = phi i1 [%arg_bad, %emit_arg_sig], [%empty_bad, %emit_empty_sig]
  %s0_failed = icmp ne i32 %s0, 0
  %s1_failed = icmp ne i32 %s1, 0
  %bad01 = or i1 %s0_failed, %s1_failed
  %bad = or i1 %bad01, %tail_bad
  br i1 %bad, label %fail, label %success

success:
  %void_value = call i64 @weave_emit_void_value()
  ret i64 %void_value

fail:
  ret i64 -9223372036854775808
}

; ----------------------------------------------------------------------------
; weave_emit_cast_expr
; ----------------------------------------------------------------------------

define i64 @weave_emit_cast_expr(ptr %ctx, i64 %node_index) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %expr_node = call i64 @weave_ast_a(ptr %ast, i64 %node_index)
  %value = call i64 @weave_emit_expr(ptr %ctx, i64 %expr_node)
  %failed = icmp eq i64 %value, -9223372036854775808
  br i1 %failed, label %fail, label %emit

emit:
  %temp = call i64 @weave_emit_next_temp(ptr %ctx)
  %s0 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.tmp_prefix)
  %temp_i32 = trunc i64 %temp to i32
  %s1 = call i32 @weave_emit_i32(ptr %ctx, i32 %temp_i32)
  %s2 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.trunc_i64)
  %s3 = call i32 @weave_emit_operand(ptr %ctx, i64 %value)
  %s4 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.to_i32)
  %s5 = call i32 @weave_emit_newline(ptr %ctx)
  %s0_failed = icmp ne i32 %s0, 0
  %s1_failed = icmp ne i32 %s1, 0
  %s2_failed = icmp ne i32 %s2, 0
  %s3_failed = icmp ne i32 %s3, 0
  %s4_failed = icmp ne i32 %s4, 0
  %s5_failed = icmp ne i32 %s5, 0
  %bad01 = or i1 %s0_failed, %s1_failed
  %bad23 = or i1 %s2_failed, %s3_failed
  %bad45 = or i1 %s4_failed, %s5_failed
  %bad0123 = or i1 %bad01, %bad23
  %bad = or i1 %bad0123, %bad45
  br i1 %bad, label %fail, label %success

success:
  ret i64 %temp

fail:
  ret i64 -9223372036854775808
}

; ----------------------------------------------------------------------------
; weave_emit_return_stmt
; ----------------------------------------------------------------------------

define i32 @weave_emit_return_stmt(ptr %ctx, i64 %node_index) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %expr_node = call i64 @weave_ast_a(ptr %ast, i64 %node_index)
  %value = call i64 @weave_emit_expr(ptr %ctx, i64 %expr_node)
  %failed = icmp eq i64 %value, -9223372036854775808
  br i1 %failed, label %fail, label %emit

emit:
  %return_type = call i32 @weave_emit_return_type(ptr %ctx)
  %is_i64 = icmp eq i32 %return_type, 39
  br i1 %is_i64, label %emit_i64, label %check_ptr

check_ptr:
  %is_ptr = icmp eq i32 %return_type, 58
  br i1 %is_ptr, label %emit_ptr, label %emit_i32

emit_i32:
  %s0_i32 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.ret_i32)
  %s1_i32 = call i32 @weave_emit_operand(ptr %ctx, i64 %value)
  %s2_i32 = call i32 @weave_emit_newline(ptr %ctx)
  %s0_i32_failed = icmp ne i32 %s0_i32, 0
  %s1_i32_failed = icmp ne i32 %s1_i32, 0
  %s2_i32_failed = icmp ne i32 %s2_i32, 0
  %bad_i32_01 = or i1 %s0_i32_failed, %s1_i32_failed
  %bad_i32 = or i1 %bad_i32_01, %s2_i32_failed
  br i1 %bad_i32, label %fail, label %success

emit_i64:
  %s0_i64 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.ret_i64)
  %s1_i64 = call i32 @weave_emit_operand(ptr %ctx, i64 %value)
  %s2_i64 = call i32 @weave_emit_newline(ptr %ctx)
  %s0_i64_failed = icmp ne i32 %s0_i64, 0
  %s1_i64_failed = icmp ne i32 %s1_i64, 0
  %s2_i64_failed = icmp ne i32 %s2_i64, 0
  %bad_i64_01 = or i1 %s0_i64_failed, %s1_i64_failed
  %bad_i64 = or i1 %bad_i64_01, %s2_i64_failed
  br i1 %bad_i64, label %fail, label %success

emit_ptr:
  %s0_ptr = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.ret_ptr)
  %s1_ptr = call i32 @weave_emit_operand(ptr %ctx, i64 %value)
  %s2_ptr = call i32 @weave_emit_newline(ptr %ctx)
  %s0_ptr_failed = icmp ne i32 %s0_ptr, 0
  %s1_ptr_failed = icmp ne i32 %s1_ptr, 0
  %s2_ptr_failed = icmp ne i32 %s2_ptr, 0
  %bad_ptr_01 = or i1 %s0_ptr_failed, %s1_ptr_failed
  %bad_ptr = or i1 %bad_ptr_01, %s2_ptr_failed
  br i1 %bad_ptr, label %fail, label %success

success:
  ret i32 0

fail:
  ret i32 1
}

; ----------------------------------------------------------------------------
; weave_emit_return_void_stmt
; ----------------------------------------------------------------------------

define i32 @weave_emit_return_void_stmt(ptr %ctx, i64 %node_index) {
entry:
  %s0 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.ret_void)
  %failed = icmp ne i32 %s0, 0
  br i1 %failed, label %fail, label %success

success:
  ret i32 0

fail:
  ret i32 1
}

; ----------------------------------------------------------------------------
; weave_emit_let_stmt
; ----------------------------------------------------------------------------

define i32 @weave_emit_let_stmt(ptr %ctx, i64 %node_index) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %expr_node = call i64 @weave_ast_a(ptr %ast, i64 %node_index)
  %type_wide = call i64 @weave_ast_b(ptr %ast, i64 %node_index)
  %name_start = call i64 @weave_ast_text_start(ptr %ast, i64 %node_index)
  %name_len = call i64 @weave_ast_text_len(ptr %ast, i64 %node_index)
  %type_kind = trunc i64 %type_wide to i32
  %is_ptr = icmp eq i32 %type_kind, 58

  %value = call i64 @weave_emit_expr(ptr %ctx, i64 %expr_node)
  %failed = icmp eq i64 %value, -9223372036854775808
  br i1 %failed, label %fail, label %emit_assignment

emit_assignment:
  %s0 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.percent)
  br i1 %is_ptr, label %emit_ptr, label %check_i64

check_i64:
  %is_i64 = icmp eq i32 %type_kind, 39
  br i1 %is_i64, label %emit_i64, label %emit_i32

emit_i32:
  %s1_i32 = call i32 @weave_emit_source_slice(ptr %ctx, i64 %name_start, i64 %name_len)
  %s2_i32 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.alloca_i32)
  %s3_i32 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.store_i32)
  %s4_i32 = call i32 @weave_emit_operand(ptr %ctx, i64 %value)
  %s5_i32 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.comma_ptr_percent)
  %s6_i32 = call i32 @weave_emit_source_slice(ptr %ctx, i64 %name_start, i64 %name_len)
  %s7_i32 = call i32 @weave_emit_newline(ptr %ctx)
  %s0_failed = icmp ne i32 %s0, 0
  %s1_failed = icmp ne i32 %s1_i32, 0
  %s2_failed = icmp ne i32 %s2_i32, 0
  %s3_failed = icmp ne i32 %s3_i32, 0
  %s4_failed = icmp ne i32 %s4_i32, 0
  %s5_failed = icmp ne i32 %s5_i32, 0
  %s6_failed = icmp ne i32 %s6_i32, 0
  %s7_failed = icmp ne i32 %s7_i32, 0
  %bad01 = or i1 %s0_failed, %s1_failed
  %bad23 = or i1 %s2_failed, %s3_failed
  %bad45 = or i1 %s4_failed, %s5_failed
  %bad67 = or i1 %s6_failed, %s7_failed
  %bad0123 = or i1 %bad01, %bad23
  %bad012345 = or i1 %bad0123, %bad45
  %bad = or i1 %bad012345, %bad67
  br i1 %bad, label %fail, label %success

emit_i64:
  %s1_i64 = call i32 @weave_emit_source_slice(ptr %ctx, i64 %name_start, i64 %name_len)
  %s2_i64 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.alloca_i64)
  %s3_i64 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.store_i64)
  %s4_i64 = call i32 @weave_emit_operand(ptr %ctx, i64 %value)
  %s5_i64 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.comma_ptr_percent)
  %s6_i64 = call i32 @weave_emit_source_slice(ptr %ctx, i64 %name_start, i64 %name_len)
  %s7_i64 = call i32 @weave_emit_newline(ptr %ctx)
  %t0_failed = icmp ne i32 %s0, 0
  %t1_failed = icmp ne i32 %s1_i64, 0
  %t2_failed = icmp ne i32 %s2_i64, 0
  %t3_failed = icmp ne i32 %s3_i64, 0
  %t4_failed = icmp ne i32 %s4_i64, 0
  %t5_failed = icmp ne i32 %s5_i64, 0
  %t6_failed = icmp ne i32 %s6_i64, 0
  %t7_failed = icmp ne i32 %s7_i64, 0
  %tb01 = or i1 %t0_failed, %t1_failed
  %tb23 = or i1 %t2_failed, %t3_failed
  %tb45 = or i1 %t4_failed, %t5_failed
  %tb67 = or i1 %t6_failed, %t7_failed
  %tb0123 = or i1 %tb01, %tb23
  %tb4567 = or i1 %tb45, %tb67
  %tb = or i1 %tb0123, %tb4567
  br i1 %tb, label %fail, label %success

emit_ptr:
  %s1_ptr = call i32 @weave_emit_source_slice(ptr %ctx, i64 %name_start, i64 %name_len)
  %s2_ptr = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.alloca_ptr)
  %s3_ptr = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.store_ptr)
  %s4_ptr = call i32 @weave_emit_operand(ptr %ctx, i64 %value)
  %s5_ptr = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.comma_ptr_percent)
  %s6_ptr = call i32 @weave_emit_source_slice(ptr %ctx, i64 %name_start, i64 %name_len)
  %s7_ptr = call i32 @weave_emit_newline(ptr %ctx)
  %p0_failed = icmp ne i32 %s0, 0
  %p1_failed = icmp ne i32 %s1_ptr, 0
  %p2_failed = icmp ne i32 %s2_ptr, 0
  %p3_failed = icmp ne i32 %s3_ptr, 0
  %p4_failed = icmp ne i32 %s4_ptr, 0
  %p5_failed = icmp ne i32 %s5_ptr, 0
  %p6_failed = icmp ne i32 %s6_ptr, 0
  %p7_failed = icmp ne i32 %s7_ptr, 0
  %pb01 = or i1 %p0_failed, %p1_failed
  %pb23 = or i1 %p2_failed, %p3_failed
  %pb45 = or i1 %p4_failed, %p5_failed
  %pb67 = or i1 %p6_failed, %p7_failed
  %pb0123 = or i1 %pb01, %pb23
  %pb4567 = or i1 %pb45, %pb67
  %pb = or i1 %pb0123, %pb4567
  br i1 %pb, label %fail, label %success

success:
  ret i32 0

fail:
  ret i32 1
}

; ----------------------------------------------------------------------------
; weave_emit_set_stmt
; ----------------------------------------------------------------------------

define i32 @weave_emit_set_stmt(ptr %ctx, i64 %node_index) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %expr_node = call i64 @weave_ast_a(ptr %ast, i64 %node_index)
  %name_start = call i64 @weave_ast_text_start(ptr %ast, i64 %node_index)
  %name_len = call i64 @weave_ast_text_len(ptr %ast, i64 %node_index)
  %type_kind = call i32 @weave_emit_lookup_local_type(ptr %ctx, i64 %name_start, i64 %name_len)
  %is_ptr = icmp eq i32 %type_kind, 58

  %value = call i64 @weave_emit_expr(ptr %ctx, i64 %expr_node)
  %failed = icmp eq i64 %value, -9223372036854775808
  br i1 %failed, label %fail, label %emit_store

emit_store:
  br i1 %is_ptr, label %emit_ptr, label %check_i64

check_i64:
  %is_i64 = icmp eq i32 %type_kind, 39
  br i1 %is_i64, label %emit_i64, label %emit_i32

emit_i32:
  %s0_i32 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.store_i32)
  %s1_i32 = call i32 @weave_emit_operand(ptr %ctx, i64 %value)
  %s2_i32 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.comma_ptr_percent)
  %s3_i32 = call i32 @weave_emit_source_slice(ptr %ctx, i64 %name_start, i64 %name_len)
  %s4_i32 = call i32 @weave_emit_newline(ptr %ctx)
  %c0_failed = icmp ne i32 %s0_i32, 0
  %c1_failed = icmp ne i32 %s1_i32, 0
  %c2_failed = icmp ne i32 %s2_i32, 0
  %c3_failed = icmp ne i32 %s3_i32, 0
  %c4_failed = icmp ne i32 %s4_i32, 0
  %cb01 = or i1 %c0_failed, %c1_failed
  %cb23 = or i1 %c2_failed, %c3_failed
  %cb = or i1 %cb01, %cb23
  %cb2 = or i1 %cb, %c4_failed
  br i1 %cb2, label %fail, label %success

emit_i64:
  %s0_i64 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.store_i64)
  %s1_i64 = call i32 @weave_emit_operand(ptr %ctx, i64 %value)
  %s2_i64 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.comma_ptr_percent)
  %s3_i64 = call i32 @weave_emit_source_slice(ptr %ctx, i64 %name_start, i64 %name_len)
  %s4_i64 = call i32 @weave_emit_newline(ptr %ctx)
  %d0_failed = icmp ne i32 %s0_i64, 0
  %d1_failed = icmp ne i32 %s1_i64, 0
  %d2_failed = icmp ne i32 %s2_i64, 0
  %d3_failed = icmp ne i32 %s3_i64, 0
  %d4_failed = icmp ne i32 %s4_i64, 0
  %db01 = or i1 %d0_failed, %d1_failed
  %db23 = or i1 %d2_failed, %d3_failed
  %db = or i1 %db01, %db23
  %db2 = or i1 %db, %d4_failed
  br i1 %db2, label %fail, label %success

emit_ptr:
  %s0_ptr = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.store_ptr)
  %s1_ptr = call i32 @weave_emit_operand(ptr %ctx, i64 %value)
  %s2_ptr = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.comma_ptr_percent)
  %s3_ptr = call i32 @weave_emit_source_slice(ptr %ctx, i64 %name_start, i64 %name_len)
  %s4_ptr = call i32 @weave_emit_newline(ptr %ctx)
  %p0_failed = icmp ne i32 %s0_ptr, 0
  %p1_failed = icmp ne i32 %s1_ptr, 0
  %p2_failed = icmp ne i32 %s2_ptr, 0
  %p3_failed = icmp ne i32 %s3_ptr, 0
  %p4_failed = icmp ne i32 %s4_ptr, 0
  %pb01 = or i1 %p0_failed, %p1_failed
  %pb23 = or i1 %p2_failed, %p3_failed
  %pb = or i1 %pb01, %pb23
  %pb2 = or i1 %pb, %p4_failed
  br i1 %pb2, label %fail, label %success

success:
  ret i32 0

fail:
  ret i32 1
}

; ----------------------------------------------------------------------------
; weave_emit_store_i64_stmt
; ----------------------------------------------------------------------------

define i32 @weave_emit_store_i64_stmt(ptr %ctx, i64 %node_index) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %ptr_node = call i64 @weave_ast_a(ptr %ast, i64 %node_index)
  %value_node = call i64 @weave_ast_b(ptr %ast, i64 %node_index)
  %ptr_value = call i64 @weave_emit_expr(ptr %ctx, i64 %ptr_node)
  %ptr_failed = icmp eq i64 %ptr_value, -9223372036854775808
  br i1 %ptr_failed, label %fail, label %value

value:
  %stored_value = call i64 @weave_emit_expr(ptr %ctx, i64 %value_node)
  %value_failed = icmp eq i64 %stored_value, -9223372036854775808
  br i1 %value_failed, label %fail, label %emit

emit:
  %s0 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.store_i64)
  %s1 = call i32 @weave_emit_operand(ptr %ctx, i64 %stored_value)
  %s2 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.comma_ptr)
  %s3 = call i32 @weave_emit_operand(ptr %ctx, i64 %ptr_value)
  %s4 = call i32 @weave_emit_newline(ptr %ctx)
  %s0_failed = icmp ne i32 %s0, 0
  %s1_failed = icmp ne i32 %s1, 0
  %s2_failed = icmp ne i32 %s2, 0
  %s3_failed = icmp ne i32 %s3, 0
  %s4_failed = icmp ne i32 %s4, 0
  %bad01 = or i1 %s0_failed, %s1_failed
  %bad23 = or i1 %s2_failed, %s3_failed
  %bad0123 = or i1 %bad01, %bad23
  %bad = or i1 %bad0123, %s4_failed
  br i1 %bad, label %fail, label %success

success:
  ret i32 0

fail:
  ret i32 1
}

; ----------------------------------------------------------------------------
; weave_emit_store_i8_stmt
; ----------------------------------------------------------------------------

define i32 @weave_emit_store_i8_stmt(ptr %ctx, i64 %node_index) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %ptr_node = call i64 @weave_ast_a(ptr %ast, i64 %node_index)
  %value_node = call i64 @weave_ast_b(ptr %ast, i64 %node_index)
  %ptr_value = call i64 @weave_emit_expr(ptr %ctx, i64 %ptr_node)
  %ptr_failed = icmp eq i64 %ptr_value, -9223372036854775808
  br i1 %ptr_failed, label %fail, label %value

value:
  %stored_value = call i64 @weave_emit_expr(ptr %ctx, i64 %value_node)
  %value_failed = icmp eq i64 %stored_value, -9223372036854775808
  br i1 %value_failed, label %fail, label %emit

emit:
  %s0 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.store_i8)
  %s1 = call i32 @weave_emit_operand(ptr %ctx, i64 %stored_value)
  %s2 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.comma_ptr)
  %s3 = call i32 @weave_emit_operand(ptr %ctx, i64 %ptr_value)
  %s4 = call i32 @weave_emit_newline(ptr %ctx)
  %s0_failed = icmp ne i32 %s0, 0
  %s1_failed = icmp ne i32 %s1, 0
  %s2_failed = icmp ne i32 %s2, 0
  %s3_failed = icmp ne i32 %s3, 0
  %s4_failed = icmp ne i32 %s4, 0
  %bad01 = or i1 %s0_failed, %s1_failed
  %bad23 = or i1 %s2_failed, %s3_failed
  %bad0123 = or i1 %bad01, %bad23
  %bad = or i1 %bad0123, %s4_failed
  br i1 %bad, label %fail, label %success

success:
  ret i32 0

fail:
  ret i32 1
}

; ----------------------------------------------------------------------------
; weave_emit_label_name
; ----------------------------------------------------------------------------

define i32 @weave_emit_label_name(ptr %ctx, ptr %prefix, i64 %id) {
entry:
  %s0 = call i32 @weave_emit_cstr(ptr %ctx, ptr %prefix)
  %id_i32 = trunc i64 %id to i32
  %s1 = call i32 @weave_emit_i32(ptr %ctx, i32 %id_i32)
  %s0_failed = icmp ne i32 %s0, 0
  %s1_failed = icmp ne i32 %s1, 0
  %bad = or i1 %s0_failed, %s1_failed
  br i1 %bad, label %fail, label %success

success:
  ret i32 0

fail:
  ret i32 1
}

; ----------------------------------------------------------------------------
; weave_emit_if_stmt
; ----------------------------------------------------------------------------

define i32 @weave_emit_if_stmt(ptr %ctx, i64 %node_index) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %cond_node = call i64 @weave_ast_a(ptr %ast, i64 %node_index)
  %then_node = call i64 @weave_ast_b(ptr %ast, i64 %node_index)
  %else_node = call i64 @weave_ast_c(ptr %ast, i64 %node_index)

  %cond_value = call i64 @weave_emit_expr(ptr %ctx, i64 %cond_node)
  %cond_failed = icmp eq i64 %cond_value, -9223372036854775808
  br i1 %cond_failed, label %fail, label %emit_branch

emit_branch:
  %label_id = call i64 @weave_emit_next_label(ptr %ctx)
  %b0 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.br_i1)
  %b1 = call i32 @weave_emit_operand(ptr %ctx, i64 %cond_value)
  %b2 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.comma_label_percent)
  %b3 = call i32 @weave_emit_label_name(ptr %ctx, ptr @weave.emit.then_text, i64 %label_id)
  %b4 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.comma_label_percent)
  %b5 = call i32 @weave_emit_label_name(ptr %ctx, ptr @weave.emit.else_text, i64 %label_id)
  %b6 = call i32 @weave_emit_newline(ptr %ctx)
  %b0_failed = icmp ne i32 %b0, 0
  %b1_failed = icmp ne i32 %b1, 0
  %b2_failed = icmp ne i32 %b2, 0
  %b3_failed = icmp ne i32 %b3, 0
  %b4_failed = icmp ne i32 %b4, 0
  %b5_failed = icmp ne i32 %b5, 0
  %b6_failed = icmp ne i32 %b6, 0
  %branch_bad01 = or i1 %b0_failed, %b1_failed
  %branch_bad23 = or i1 %b2_failed, %b3_failed
  %branch_bad45 = or i1 %b4_failed, %b5_failed
  %branch_bad0123 = or i1 %branch_bad01, %branch_bad23
  %branch_bad012345 = or i1 %branch_bad0123, %branch_bad45
  %branch_bad = or i1 %branch_bad012345, %b6_failed
  br i1 %branch_bad, label %fail, label %then_label

then_label:
  %t0 = call i32 @weave_emit_label_name(ptr %ctx, ptr @weave.emit.then_text, i64 %label_id)
  %t1 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.colon_nl)
  %t0_failed = icmp ne i32 %t0, 0
  %t1_failed = icmp ne i32 %t1, 0
  %then_label_bad = or i1 %t0_failed, %t1_failed
  br i1 %then_label_bad, label %fail, label %then_body

then_body:
  %then_status = call i32 @weave_emit_stmt(ptr %ctx, i64 %then_node)
  %then_failed = icmp ne i32 %then_status, 0
  br i1 %then_failed, label %fail, label %else_label

else_label:
  %e0 = call i32 @weave_emit_label_name(ptr %ctx, ptr @weave.emit.else_text, i64 %label_id)
  %e1 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.colon_nl)
  %e0_failed = icmp ne i32 %e0, 0
  %e1_failed = icmp ne i32 %e1, 0
  %else_label_bad = or i1 %e0_failed, %e1_failed
  br i1 %else_label_bad, label %fail, label %else_body

else_body:
  %else_status = call i32 @weave_emit_stmt(ptr %ctx, i64 %else_node)
  %else_failed = icmp ne i32 %else_status, 0
  br i1 %else_failed, label %fail, label %success

success:
  ret i32 0

fail:
  ret i32 1
}

; ----------------------------------------------------------------------------
; weave_emit_while_stmt
; ----------------------------------------------------------------------------

define i32 @weave_emit_while_stmt(ptr %ctx, i64 %node_index) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %cond_node = call i64 @weave_ast_a(ptr %ast, i64 %node_index)
  %body_node = call i64 @weave_ast_b(ptr %ast, i64 %node_index)
  %label_id = call i64 @weave_emit_next_label(ptr %ctx)

  %j0 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.br_label)
  %j1 = call i32 @weave_emit_label_name(ptr %ctx, ptr @weave.emit.label_prefix, i64 %label_id)
  %j2 = call i32 @weave_emit_newline(ptr %ctx)
  %j0_failed = icmp ne i32 %j0, 0
  %j1_failed = icmp ne i32 %j1, 0
  %j2_failed = icmp ne i32 %j2, 0
  %j_bad01 = or i1 %j0_failed, %j1_failed
  %j_bad = or i1 %j_bad01, %j2_failed
  br i1 %j_bad, label %fail, label %cond_label

cond_label:
  %c0 = call i32 @weave_emit_label_name(ptr %ctx, ptr @weave.emit.label_prefix, i64 %label_id)
  %c1 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.colon_nl)
  %c0_failed = icmp ne i32 %c0, 0
  %c1_failed = icmp ne i32 %c1, 0
  %cond_label_bad = or i1 %c0_failed, %c1_failed
  br i1 %cond_label_bad, label %fail, label %cond_expr

cond_expr:
  %cond_value = call i64 @weave_emit_expr(ptr %ctx, i64 %cond_node)
  %cond_failed = icmp eq i64 %cond_value, -9223372036854775808
  br i1 %cond_failed, label %fail, label %cond_branch

cond_branch:
  %b0 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.br_i1)
  %b1 = call i32 @weave_emit_operand(ptr %ctx, i64 %cond_value)
  %b2 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.comma_label_percent)
  %b3 = call i32 @weave_emit_label_name(ptr %ctx, ptr @weave.emit.then_text, i64 %label_id)
  %b4 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.comma_label_percent)
  %b5 = call i32 @weave_emit_label_name(ptr %ctx, ptr @weave.emit.done_text, i64 %label_id)
  %b6 = call i32 @weave_emit_newline(ptr %ctx)
  %b0_failed = icmp ne i32 %b0, 0
  %b1_failed = icmp ne i32 %b1, 0
  %b2_failed = icmp ne i32 %b2, 0
  %b3_failed = icmp ne i32 %b3, 0
  %b4_failed = icmp ne i32 %b4, 0
  %b5_failed = icmp ne i32 %b5, 0
  %b6_failed = icmp ne i32 %b6, 0
  %branch_bad01 = or i1 %b0_failed, %b1_failed
  %branch_bad23 = or i1 %b2_failed, %b3_failed
  %branch_bad45 = or i1 %b4_failed, %b5_failed
  %branch_bad0123 = or i1 %branch_bad01, %branch_bad23
  %branch_bad012345 = or i1 %branch_bad0123, %branch_bad45
  %branch_bad = or i1 %branch_bad012345, %b6_failed
  br i1 %branch_bad, label %fail, label %body_label

body_label:
  %l0 = call i32 @weave_emit_label_name(ptr %ctx, ptr @weave.emit.then_text, i64 %label_id)
  %l1 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.colon_nl)
  %l0_failed = icmp ne i32 %l0, 0
  %l1_failed = icmp ne i32 %l1, 0
  %body_label_bad = or i1 %l0_failed, %l1_failed
  br i1 %body_label_bad, label %fail, label %body

body:
  %body_status = call i32 @weave_emit_stmt(ptr %ctx, i64 %body_node)
  %body_failed = icmp ne i32 %body_status, 0
  br i1 %body_failed, label %fail, label %back_edge

back_edge:
  %k0 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.br_label)
  %k1 = call i32 @weave_emit_label_name(ptr %ctx, ptr @weave.emit.label_prefix, i64 %label_id)
  %k2 = call i32 @weave_emit_newline(ptr %ctx)
  %k0_failed = icmp ne i32 %k0, 0
  %k1_failed = icmp ne i32 %k1, 0
  %k2_failed = icmp ne i32 %k2, 0
  %k_bad01 = or i1 %k0_failed, %k1_failed
  %k_bad = or i1 %k_bad01, %k2_failed
  br i1 %k_bad, label %fail, label %done_label

done_label:
  %d0 = call i32 @weave_emit_label_name(ptr %ctx, ptr @weave.emit.done_text, i64 %label_id)
  %d1 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.colon_nl)
  %d0_failed = icmp ne i32 %d0, 0
  %d1_failed = icmp ne i32 %d1, 0
  %done_label_bad = or i1 %d0_failed, %d1_failed
  br i1 %done_label_bad, label %fail, label %success

success:
  ret i32 0

fail:
  ret i32 1
}

; ----------------------------------------------------------------------------
; weave_emit_stmt_list
; ----------------------------------------------------------------------------

define i32 @weave_emit_stmt_list(ptr %ctx, i64 %list_node) {
entry:
  %empty = icmp slt i64 %list_node, 0
  br i1 %empty, label %success, label %emit_prev

emit_prev:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %stmt_node = call i64 @weave_ast_a(ptr %ast, i64 %list_node)
  %prev_node = call i64 @weave_ast_b(ptr %ast, i64 %list_node)
  %prev_status = call i32 @weave_emit_stmt_list(ptr %ctx, i64 %prev_node)
  %prev_failed = icmp ne i32 %prev_status, 0
  br i1 %prev_failed, label %fail, label %emit_stmt

emit_stmt:
  %status = call i32 @weave_emit_stmt(ptr %ctx, i64 %stmt_node)
  %failed = icmp ne i32 %status, 0
  br i1 %failed, label %fail, label %success

success:
  ret i32 0

fail:
  ret i32 1
}

; ----------------------------------------------------------------------------
; weave_emit_block
; ----------------------------------------------------------------------------

define i32 @weave_emit_block(ptr %ctx, i64 %node_index) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %list_head = call i64 @weave_ast_a(ptr %ast, i64 %node_index)
  %status = call i32 @weave_emit_stmt_list(ptr %ctx, i64 %list_head)
  ret i32 %status
}

; ----------------------------------------------------------------------------
; weave_emit_stmt
; ----------------------------------------------------------------------------
;
; Stage 0 emits blocks, let/set statements, return statements, and expression
; statements. More statement kinds are admitted one ladder test at a time.


define i32 @weave_emit_stmt(ptr %ctx, i64 %node_index) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %kind = call i32 @weave_ast_kind(ptr %ast, i64 %node_index)

  %is_block = icmp eq i32 %kind, 3
  br i1 %is_block, label %block_stmt, label %check_if

check_if:
  %is_if = icmp eq i32 %kind, 5
  br i1 %is_if, label %if_stmt, label %check_return_void

check_return_void:
  %is_return_void = icmp eq i32 %kind, 27
  br i1 %is_return_void, label %return_void_stmt, label %check_while

check_while:
  %is_while = icmp eq i32 %kind, 6
  br i1 %is_while, label %while_stmt, label %check_return

check_return:
  %is_return = icmp eq i32 %kind, 4
  br i1 %is_return, label %return_stmt, label %check_let

check_let:
  %is_let = icmp eq i32 %kind, 7
  br i1 %is_let, label %let_stmt, label %check_set

check_set:
  %is_set = icmp eq i32 %kind, 8
  br i1 %is_set, label %set_stmt, label %check_store_i64

check_store_i64:
  %is_store_i64 = icmp eq i32 %kind, 23
  br i1 %is_store_i64, label %store_i64_stmt, label %check_store_i8

check_store_i8:
  %is_store_i8 = icmp eq i32 %kind, 25
  br i1 %is_store_i8, label %store_i8_stmt, label %check_expr_stmt

check_expr_stmt:
  %is_expr_stmt = icmp eq i32 %kind, 14
  br i1 %is_expr_stmt, label %expr_stmt, label %raw_expr

block_stmt:
  %block_status = call i32 @weave_emit_block(ptr %ctx, i64 %node_index)
  ret i32 %block_status

if_stmt:
  %if_status = call i32 @weave_emit_if_stmt(ptr %ctx, i64 %node_index)
  ret i32 %if_status

while_stmt:
  %while_status = call i32 @weave_emit_while_stmt(ptr %ctx, i64 %node_index)
  ret i32 %while_status

return_stmt:
  %status = call i32 @weave_emit_return_stmt(ptr %ctx, i64 %node_index)
  ret i32 %status

return_void_stmt:
  %return_void_status = call i32 @weave_emit_return_void_stmt(ptr %ctx, i64 %node_index)
  ret i32 %return_void_status

let_stmt:
  %let_status = call i32 @weave_emit_let_stmt(ptr %ctx, i64 %node_index)
  ret i32 %let_status

set_stmt:
  %set_status = call i32 @weave_emit_set_stmt(ptr %ctx, i64 %node_index)
  ret i32 %set_status

store_i64_stmt:
  %store_i64_status = call i32 @weave_emit_store_i64_stmt(ptr %ctx, i64 %node_index)
  ret i32 %store_i64_status

store_i8_stmt:
  %store_i8_status = call i32 @weave_emit_store_i8_stmt(ptr %ctx, i64 %node_index)
  ret i32 %store_i8_status

expr_stmt:
  %expr_node = call i64 @weave_ast_a(ptr %ast, i64 %node_index)
  %value = call i64 @weave_emit_expr(ptr %ctx, i64 %expr_node)
  %failed = icmp eq i64 %value, -9223372036854775808
  br i1 %failed, label %fail, label %success

raw_expr:
  %value_raw = call i64 @weave_emit_expr(ptr %ctx, i64 %node_index)
  %failed_raw = icmp eq i64 %value_raw, -9223372036854775808
  br i1 %failed_raw, label %fail, label %success

success:
  ret i32 0

fail:
  ret i32 1
}

; ----------------------------------------------------------------------------
; weave_emit_function
; ----------------------------------------------------------------------------

define i32 @weave_emit_function(ptr %ctx, i64 %node_index) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %body_node = call i64 @weave_ast_a(ptr %ast, i64 %node_index)
  %param_start = call i64 @weave_ast_b(ptr %ast, i64 %node_index)
  %param_len = call i64 @weave_ast_c(ptr %ast, i64 %node_index)
  %param2_start = call i64 @weave_ast_text_start(ptr %ast, i64 %body_node)
  %param2_len = call i64 @weave_ast_text_len(ptr %ast, i64 %body_node)
  %return_type_wide = call i64 @weave_ast_c(ptr %ast, i64 %body_node)
  %return_type = trunc i64 %return_type_wide to i32
  %returns_i64 = icmp eq i32 %return_type, 39
  %returns_ptr = icmp eq i32 %return_type, 58
  %returns_void = icmp eq i32 %return_type, 59
  %name_start = call i64 @weave_ast_text_start(ptr %ast, i64 %node_index)
  %name_len = call i64 @weave_ast_text_len(ptr %ast, i64 %node_index)

  br i1 %returns_i64, label %emit_i64_define, label %check_ptr_define

check_ptr_define:
  br i1 %returns_ptr, label %emit_ptr_define, label %check_void_define

check_void_define:
  br i1 %returns_void, label %emit_void_define, label %emit_i32_define

emit_i32_define:
  %s0_i32 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.define_i32)
  br label %emit_name

emit_i64_define:
  %s0_i64 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.define_i64)
  br label %emit_name

emit_ptr_define:
  %s0_ptr = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.define_ptr)
  br label %emit_name

emit_void_define:
  %s0_void = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.define_void)
  br label %emit_name

emit_name:
  %s0 = phi i32 [%s0_i32, %emit_i32_define], [%s0_i64, %emit_i64_define], [%s0_ptr, %emit_ptr_define], [%s0_void, %emit_void_define]
  %s1 = call i32 @weave_emit_source_slice(ptr %ctx, i64 %name_start, i64 %name_len)
  %has_param = icmp ne i64 %param_len, 0
  %has_param2 = icmp ne i64 %param2_len, 0
  br i1 %has_param, label %emit_param_sig, label %emit_no_param_sig

emit_no_param_sig:
  %s2_no_param = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.fn_sig)
  br label %emit_entry

emit_param_sig:
  %s2_param_a = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.fn_sig_1_prefix)
  %s2_param_b = call i32 @weave_emit_source_slice(ptr %ctx, i64 %param_start, i64 %param_len)
  br i1 %has_param2, label %emit_param2_sig, label %emit_param1_sig_end

emit_param2_sig:
  %s2_param_mid = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.fn_sig_2_mid)
  %s2_param_d = call i32 @weave_emit_source_slice(ptr %ctx, i64 %param2_start, i64 %param2_len)
  br label %emit_param1_sig_end

emit_param1_sig_end:
  %s2_param_extra = phi i32 [0, %emit_param_sig], [%s2_param_mid, %emit_param2_sig]
  %s2_param_extra2 = phi i32 [0, %emit_param_sig], [%s2_param_d, %emit_param2_sig]
  %s2_param_c = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.fn_sig_1_suffix)
  %s2_param_a_failed = icmp ne i32 %s2_param_a, 0
  %s2_param_b_failed = icmp ne i32 %s2_param_b, 0
  %s2_param_extra_failed = icmp ne i32 %s2_param_extra, 0
  %s2_param_extra2_failed = icmp ne i32 %s2_param_extra2, 0
  %s2_param_c_failed = icmp ne i32 %s2_param_c, 0
  %s2_param_bad0 = or i1 %s2_param_a_failed, %s2_param_b_failed
  %s2_param_bad1 = or i1 %s2_param_extra_failed, %s2_param_extra2_failed
  %s2_param_bad2 = or i1 %s2_param_bad0, %s2_param_bad1
  %s2_param_bad = or i1 %s2_param_bad2, %s2_param_c_failed
  br label %emit_entry

emit_entry:
  %s2 = phi i32 [%s2_no_param, %emit_no_param_sig], [0, %emit_param1_sig_end]
  %s2_param_failed = phi i1 [false, %emit_no_param_sig], [%s2_param_bad, %emit_param1_sig_end]
  %s3 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.entry)

  %s0_failed = icmp ne i32 %s0, 0
  %s1_failed = icmp ne i32 %s1, 0
  %s2_failed = icmp ne i32 %s2, 0
  %s3_failed = icmp ne i32 %s3, 0
  %head_bad0 = or i1 %s0_failed, %s1_failed
  %head_bad1 = or i1 %s2_failed, %s3_failed
  %head_bad2 = or i1 %head_bad1, %s2_param_failed
  %head_bad = or i1 %head_bad0, %head_bad2
  br i1 %head_bad, label %fail, label %maybe_init_param

maybe_init_param:
  br i1 %has_param, label %init_param, label %body

init_param:
  %p0 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.percent)
  %p1 = call i32 @weave_emit_source_slice(ptr %ctx, i64 %param_start, i64 %param_len)
  %p2 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.alloca_i32)
  %p3 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.store_i32)
  %p4 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.percent)
  %p5 = call i32 @weave_emit_source_slice(ptr %ctx, i64 %param_start, i64 %param_len)
  %p6 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.arg_suffix)
  %p7 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.comma_ptr_percent)
  %p8 = call i32 @weave_emit_source_slice(ptr %ctx, i64 %param_start, i64 %param_len)
  %p9 = call i32 @weave_emit_newline(ptr %ctx)
  %p0_failed = icmp ne i32 %p0, 0
  %p1_failed = icmp ne i32 %p1, 0
  %p2_failed = icmp ne i32 %p2, 0
  %p3_failed = icmp ne i32 %p3, 0
  %p4_failed = icmp ne i32 %p4, 0
  %p5_failed = icmp ne i32 %p5, 0
  %p6_failed = icmp ne i32 %p6, 0
  %p7_failed = icmp ne i32 %p7, 0
  %p8_failed = icmp ne i32 %p8, 0
  %p9_failed = icmp ne i32 %p9, 0
  %p_bad01 = or i1 %p0_failed, %p1_failed
  %p_bad23 = or i1 %p2_failed, %p3_failed
  %p_bad45 = or i1 %p4_failed, %p5_failed
  %p_bad67 = or i1 %p6_failed, %p7_failed
  %p_bad89 = or i1 %p8_failed, %p9_failed
  %p_bad0123 = or i1 %p_bad01, %p_bad23
  %p_bad4567 = or i1 %p_bad45, %p_bad67
  %p_bad01234567 = or i1 %p_bad0123, %p_bad4567
  %p_bad = or i1 %p_bad01234567, %p_bad89
  br i1 %p_bad, label %fail, label %maybe_init_param2

maybe_init_param2:
  br i1 %has_param2, label %init_param2, label %body

init_param2:
  %q0 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.percent)
  %q1 = call i32 @weave_emit_source_slice(ptr %ctx, i64 %param2_start, i64 %param2_len)
  %q2 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.alloca_i32)
  %q3 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.store_i32)
  %q4 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.percent)
  %q5 = call i32 @weave_emit_source_slice(ptr %ctx, i64 %param2_start, i64 %param2_len)
  %q6 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.arg_suffix)
  %q7 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.comma_ptr_percent)
  %q8 = call i32 @weave_emit_source_slice(ptr %ctx, i64 %param2_start, i64 %param2_len)
  %q9 = call i32 @weave_emit_newline(ptr %ctx)
  %q0_failed = icmp ne i32 %q0, 0
  %q1_failed = icmp ne i32 %q1, 0
  %q2_failed = icmp ne i32 %q2, 0
  %q3_failed = icmp ne i32 %q3, 0
  %q4_failed = icmp ne i32 %q4, 0
  %q5_failed = icmp ne i32 %q5, 0
  %q6_failed = icmp ne i32 %q6, 0
  %q7_failed = icmp ne i32 %q7, 0
  %q8_failed = icmp ne i32 %q8, 0
  %q9_failed = icmp ne i32 %q9, 0
  %q_bad01 = or i1 %q0_failed, %q1_failed
  %q_bad23 = or i1 %q2_failed, %q3_failed
  %q_bad45 = or i1 %q4_failed, %q5_failed
  %q_bad67 = or i1 %q6_failed, %q7_failed
  %q_bad89 = or i1 %q8_failed, %q9_failed
  %q_bad0123 = or i1 %q_bad01, %q_bad23
  %q_bad4567 = or i1 %q_bad45, %q_bad67
  %q_bad01234567 = or i1 %q_bad0123, %q_bad4567
  %q_bad = or i1 %q_bad01234567, %q_bad89
  br i1 %q_bad, label %fail, label %body

body:
  call void @weave_emit_set_return_type(ptr %ctx, i32 %return_type)
  %body_status = call i32 @weave_emit_stmt(ptr %ctx, i64 %body_node)
  %body_failed = icmp ne i32 %body_status, 0
  br i1 %body_failed, label %fail, label %close

close:
  %s4 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.close_fn)
  %close_failed = icmp ne i32 %s4, 0
  br i1 %close_failed, label %fail, label %success

success:
  ret i32 0

fail:
  ret i32 1
}

; ----------------------------------------------------------------------------
; weave_emit_program
; ----------------------------------------------------------------------------
;
; Stage 0 scans the compact AST and emits nodes whose kind is AST_FUNCTION.
; Function nodes are not contiguous because each function body is parsed before
; the function wrapper node is appended.


define i32 @weave_emit_program(ptr %ctx, i64 %program_node) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %node_count = call i64 @weave_ast_count(ptr %ast)

  %header_status = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.module_header)
  %header_failed = icmp ne i32 %header_status, 0
  br i1 %header_failed, label %fail, label %emit_strings

emit_strings:
  %strings_status = call i32 @weave_emit_string_globals(ptr %ctx)
  %strings_failed = icmp ne i32 %strings_status, 0
  br i1 %strings_failed, label %fail, label %loop

loop:
  %i = phi i64 [0, %emit_strings], [%next_i, %after_node]
  %done = icmp uge i64 %i, %node_count
  br i1 %done, label %success, label %check_node

check_node:
  %kind = call i32 @weave_ast_kind(ptr %ast, i64 %i)
  %is_function = icmp eq i32 %kind, 2
  br i1 %is_function, label %emit_function, label %after_node

emit_function:
  %status = call i32 @weave_emit_function(ptr %ctx, i64 %i)
  %failed = icmp ne i32 %status, 0
  br i1 %failed, label %fail, label %after_node

after_node:
  %next_i = add i64 %i, 1
  br label %loop

success:
  ret i32 0

fail:
  ret i32 1
}

; ----------------------------------------------------------------------------
; weave_emit_llvm
;
; Public emitter entry point.
;
; Returns:
;   0 on success
;   1 on failure
; ----------------------------------------------------------------------------

define i32 @weave_emit_llvm(ptr %source, ptr %ast, i64 %program_node, ptr %out) {
entry:
  %ctx_storage = alloca %weave.EmitContext
  call void @weave_emit_context_init(ptr %ctx_storage, ptr %source, ptr %ast, ptr %out)
  %status = call i32 @weave_emit_program(ptr %ctx_storage, i64 %program_node)
  ret i32 %status
}
