; =============================================================================
; Weave Stage 0 Bootstrap Compiler
; 07_emit_llvm.ll
;
; Minimal LLVM IR emitter for the Stage 0 bootstrap subset.
;
; Responsibility:
;
;     AST -> LLVM IR text
;
; The emitter intentionally targets only small i32 programs. It is not an
; optimizer, verifier, type checker, or production backend.
; =============================================================================

; ----------------------------------------------------------------------------
; Emit context
; ----------------------------------------------------------------------------
;
; Stage 0 keeps the emitter state deliberately small.
;
; %weave.EmitContext = type {
;   ptr, ; source : %weave.Source*
;   ptr, ; ast    : %weave.Ast*
;   ptr, ; out    : %weave.Buffer*
;   i64, ; temp counter
;   i64  ; label counter
; }

%weave.EmitContext = type { ptr, ptr, ptr, i64, i64 }

; ----------------------------------------------------------------------------
; Emit context accessors
; ----------------------------------------------------------------------------

define ptr @weave_emit_source_ptr(ptr %ctx) {
entry:
  %field = getelementptr inbounds %weave.EmitContext, ptr %ctx, i32 0, i32 0
  ret ptr %field
}

define ptr @weave_emit_ast_ptr(ptr %ctx) {
entry:
  %field = getelementptr inbounds %weave.EmitContext, ptr %ctx, i32 0, i32 1
  ret ptr %field
}

define ptr @weave_emit_out_ptr(ptr %ctx) {
entry:
  %field = getelementptr inbounds %weave.EmitContext, ptr %ctx, i32 0, i32 2
  ret ptr %field
}

define ptr @weave_emit_temp_counter_ptr(ptr %ctx) {
entry:
  %field = getelementptr inbounds %weave.EmitContext, ptr %ctx, i32 0, i32 3
  ret ptr %field
}

define ptr @weave_emit_label_counter_ptr(ptr %ctx) {
entry:
  %field = getelementptr inbounds %weave.EmitContext, ptr %ctx, i32 0, i32 4
  ret ptr %field
}

define ptr @weave_emit_source(ptr %ctx) {
entry:
  %field = call ptr @weave_emit_source_ptr(ptr %ctx)
  %value = load ptr, ptr %field
  ret ptr %value
}

define ptr @weave_emit_ast(ptr %ctx) {
entry:
  %field = call ptr @weave_emit_ast_ptr(ptr %ctx)
  %value = load ptr, ptr %field
  ret ptr %value
}

define ptr @weave_emit_out(ptr %ctx) {
entry:
  %field = call ptr @weave_emit_out_ptr(ptr %ctx)
  %value = load ptr, ptr %field
  ret ptr %value
}

; ----------------------------------------------------------------------------
; weave_emit_context_init
; ----------------------------------------------------------------------------

define void @weave_emit_context_init(ptr %ctx, ptr %source, ptr %ast, ptr %out) {
entry:
  %source_field = call ptr @weave_emit_source_ptr(ptr %ctx)
  %ast_field = call ptr @weave_emit_ast_ptr(ptr %ctx)
  %out_field = call ptr @weave_emit_out_ptr(ptr %ctx)
  %temp_field = call ptr @weave_emit_temp_counter_ptr(ptr %ctx)
  %label_field = call ptr @weave_emit_label_counter_ptr(ptr %ctx)

  store ptr %source, ptr %source_field
  store ptr %ast, ptr %ast_field
  store ptr %out, ptr %out_field
  store i64 0, ptr %temp_field
  store i64 0, ptr %label_field
  ret void
}

; ----------------------------------------------------------------------------
; Text append helpers
; ----------------------------------------------------------------------------

define i32 @weave_emit_cstr(ptr %ctx, ptr %text) {
entry:
  %out = call ptr @weave_emit_out(ptr %ctx)
  %status = call i32 @weave_buffer_append_cstr(ptr %out, ptr %text)
  ret i32 %status
}

define i32 @weave_emit_byte(ptr %ctx, i32 %byte) {
entry:
  %out = call ptr @weave_emit_out(ptr %ctx)
  %status = call i32 @weave_buffer_append_byte(ptr %out, i32 %byte)
  ret i32 %status
}

define i32 @weave_emit_i32(ptr %ctx, i32 %value) {
entry:
  %out = call ptr @weave_emit_out(ptr %ctx)
  %status = call i32 @weave_buffer_append_i32(ptr %out, i32 %value)
  ret i32 %status
}

define i32 @weave_emit_newline(ptr %ctx) {
entry:
  %status = call i32 @weave_emit_byte(ptr %ctx, i32 10)
  ret i32 %status
}

; ----------------------------------------------------------------------------
; String constants used by emitter
; ----------------------------------------------------------------------------

@weave.emit.module_header = private unnamed_addr constant [53 x i8] c"; generated by weavec0, the Weave Stage 0 compiler\0A\0A\00"
@weave.emit.define_i32 = private unnamed_addr constant [13 x i8] c"define i32 @\00"
@weave.emit.fn_sig = private unnamed_addr constant [6 x i8] c"() {\0A\00"
@weave.emit.fn_sig_1_prefix = private unnamed_addr constant [7 x i8] c"(i32 %\00"
@weave.emit.fn_sig_1_suffix = private unnamed_addr constant [5 x i8] c") {\0A\00"
@weave.emit.entry = private unnamed_addr constant [8 x i8] c"entry:\0A\00"
@weave.emit.ret_i32 = private unnamed_addr constant [11 x i8] c"  ret i32 \00"
@weave.emit.close_fn = private unnamed_addr constant [4 x i8] c"}\0A\0A\00"
@weave.emit.tmp_prefix = private unnamed_addr constant [3 x i8] c"%t\00"
@weave.emit.percent = private unnamed_addr constant [2 x i8] c"%\00"
@weave.emit.label_prefix = private unnamed_addr constant [6 x i8] c"label\00"
@weave.emit.eq = private unnamed_addr constant [12 x i8] c" = add i32 \00"
@weave.emit.add = private unnamed_addr constant [12 x i8] c" = add i32 \00"
@weave.emit.sub = private unnamed_addr constant [12 x i8] c" = sub i32 \00"
@weave.emit.mul = private unnamed_addr constant [12 x i8] c" = mul i32 \00"
@weave.emit.div = private unnamed_addr constant [13 x i8] c" = sdiv i32 \00"
@weave.emit.icmp_eq = private unnamed_addr constant [16 x i8] c" = icmp eq i32 \00"
@weave.emit.icmp_ne = private unnamed_addr constant [16 x i8] c" = icmp ne i32 \00"
@weave.emit.icmp_lt = private unnamed_addr constant [17 x i8] c" = icmp slt i32 \00"
@weave.emit.icmp_le = private unnamed_addr constant [17 x i8] c" = icmp sle i32 \00"
@weave.emit.icmp_gt = private unnamed_addr constant [17 x i8] c" = icmp sgt i32 \00"
@weave.emit.icmp_ge = private unnamed_addr constant [17 x i8] c" = icmp sge i32 \00"
@weave.emit.comma_i32 = private unnamed_addr constant [3 x i8] c", \00"
@weave.emit.br_i1 = private unnamed_addr constant [11 x i8] c"  br i1 %t\00"
@weave.emit.br_label = private unnamed_addr constant [13 x i8] c"  br label %\00"
@weave.emit.then_text = private unnamed_addr constant [5 x i8] c"then\00"
@weave.emit.else_text = private unnamed_addr constant [5 x i8] c"else\00"
@weave.emit.done_text = private unnamed_addr constant [5 x i8] c"done\00"
@weave.emit.colon_nl = private unnamed_addr constant [3 x i8] c":\0A\00"
@weave.emit.space = private unnamed_addr constant [2 x i8] c" \00"
@weave.emit.call_i32 = private unnamed_addr constant [14 x i8] c" = call i32 @\00"
@weave.emit.call_sig_1 = private unnamed_addr constant [6 x i8] c"(i32 \00"
@weave.emit.call_sig_end = private unnamed_addr constant [3 x i8] c")\0A\00"

; ----------------------------------------------------------------------------
; Counter helpers
; ----------------------------------------------------------------------------

define i64 @weave_emit_next_temp(ptr %ctx) {
entry:
  %field = call ptr @weave_emit_temp_counter_ptr(ptr %ctx)
  %old = load i64, ptr %field
  %next = add i64 %old, 1
  store i64 %next, ptr %field
  ret i64 %old
}

define i64 @weave_emit_next_label(ptr %ctx) {
entry:
  %field = call ptr @weave_emit_label_counter_ptr(ptr %ctx)
  %old = load i64, ptr %field
  %next = add i64 %old, 1
  store i64 %next, ptr %field
  ret i64 %old
}

; ----------------------------------------------------------------------------
; Source slice emission
; ----------------------------------------------------------------------------
;
; Append source bytes [start, start + length) to the output.
;
; Used for function names and call names. Stage 0 assumes trusted bootstrap
; source and does not yet sanitize identifiers.


define i32 @weave_emit_source_slice(ptr %ctx, i64 %start, i64 %length) {
entry:
  %source = call ptr @weave_emit_source(ptr %ctx)
  %data = call ptr @weave_source_data(ptr %source)
  %slice = getelementptr inbounds i8, ptr %data, i64 %start
  %out = call ptr @weave_emit_out(ptr %ctx)
  %status = call i32 @weave_buffer_append_bytes(ptr %out, ptr %slice, i64 %length)
  ret i32 %status
}

; ----------------------------------------------------------------------------
; Value representation
; ----------------------------------------------------------------------------
;
; Expressions return a compact emitted-value descriptor:
;
;   >= 0 : temporary id %tN
;   <  0 : immediate i32 value encoded as -(value + 1)
;
; This lets Stage 0 avoid a richer value object while still emitting readable IR.
;
; Note: this encoding is primitive and only intended for small bootstrap tests.


define i64 @weave_emit_immediate_value(i32 %value) {
entry:
  %wide = sext i32 %value to i64
  %plus_one = add i64 %wide, 1
  %encoded = sub i64 0, %plus_one
  ret i64 %encoded
}

define i32 @weave_emitted_value_is_temp(i64 %value) {
entry:
  %is_temp = icmp sge i64 %value, 0
  br i1 %is_temp, label %yes, label %no

yes:
  ret i32 1

no:
  ret i32 0
}

define i32 @weave_emitted_value_immediate_i32(i64 %value) {
entry:
  %neg = sub i64 0, %value
  %minus_one = sub i64 %neg, 1
  %narrow = trunc i64 %minus_one to i32
  ret i32 %narrow
}

; ----------------------------------------------------------------------------
; Emit an i32 operand.
; ----------------------------------------------------------------------------
;
; Operand may be either an immediate value or a temp id.


define i32 @weave_emit_operand(ptr %ctx, i64 %value) {
entry:
  %is_temp_i32 = call i32 @weave_emitted_value_is_temp(i64 %value)
  %is_temp = icmp ne i32 %is_temp_i32, 0
  br i1 %is_temp, label %temp, label %immediate

temp:
  %s0 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.tmp_prefix)
  %temp_i32 = trunc i64 %value to i32
  %s1 = call i32 @weave_emit_i32(ptr %ctx, i32 %temp_i32)
  %s0_failed = icmp ne i32 %s0, 0
  %s1_failed = icmp ne i32 %s1, 0
  %bad0 = or i1 %s0_failed, %s1_failed
  br i1 %bad0, label %fail, label %success

immediate:
  %imm = call i32 @weave_emitted_value_immediate_i32(i64 %value)
  %s2 = call i32 @weave_emit_i32(ptr %ctx, i32 %imm)
  %bad1 = icmp ne i32 %s2, 0
  br i1 %bad1, label %fail, label %success

success:
  ret i32 0

fail:
  ret i32 1
}

; ----------------------------------------------------------------------------
; Emit an expression as an instruction operand.
; ----------------------------------------------------------------------------

define i32 @weave_emit_expr_operand(ptr %ctx, i64 %node_index) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %kind = call i32 @weave_ast_kind(ptr %ast, i64 %node_index)
  %is_name = icmp eq i32 %kind, 13
  br i1 %is_name, label %name, label %value

name:
  %name_start = call i64 @weave_ast_text_start(ptr %ast, i64 %node_index)
  %name_len = call i64 @weave_ast_text_len(ptr %ast, i64 %node_index)
  %s0 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.percent)
  %s1 = call i32 @weave_emit_source_slice(ptr %ctx, i64 %name_start, i64 %name_len)
  %s0_failed = icmp ne i32 %s0, 0
  %s1_failed = icmp ne i32 %s1, 0
  %bad = or i1 %s0_failed, %s1_failed
  br i1 %bad, label %fail, label %success

value:
  %emitted = call i64 @weave_emit_expr(ptr %ctx, i64 %node_index)
  %failed = icmp eq i64 %emitted, -9223372036854775808
  br i1 %failed, label %fail, label %emit_operand

emit_operand:
  %status = call i32 @weave_emit_operand(ptr %ctx, i64 %emitted)
  %operand_failed = icmp ne i32 %status, 0
  br i1 %operand_failed, label %fail, label %success

success:
  ret i32 0

fail:
  ret i32 1
}

; ----------------------------------------------------------------------------
; Emit binary expression
; ----------------------------------------------------------------------------


define i64 @weave_emit_binary_expr(ptr %ctx, i64 %node_index) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %op_wide = call i64 @weave_ast_a(ptr %ast, i64 %node_index)
  %lhs_node = call i64 @weave_ast_b(ptr %ast, i64 %node_index)
  %rhs_node = call i64 @weave_ast_c(ptr %ast, i64 %node_index)

  %lhs_kind = call i32 @weave_ast_kind(ptr %ast, i64 %lhs_node)
  %lhs_is_name = icmp eq i32 %lhs_kind, 13
  br i1 %lhs_is_name, label %rhs, label %emit_lhs

emit_lhs:
  %lhs_value = call i64 @weave_emit_expr(ptr %ctx, i64 %lhs_node)
  %lhs_failed = icmp eq i64 %lhs_value, -9223372036854775808
  br i1 %lhs_failed, label %fail, label %rhs

rhs:
  %rhs_kind = call i32 @weave_ast_kind(ptr %ast, i64 %rhs_node)
  %rhs_is_name = icmp eq i32 %rhs_kind, 13
  br i1 %rhs_is_name, label %emit, label %emit_rhs

emit_rhs:
  %rhs_value = call i64 @weave_emit_expr(ptr %ctx, i64 %rhs_node)
  %rhs_failed = icmp eq i64 %rhs_value, -9223372036854775808
  br i1 %rhs_failed, label %fail, label %emit

emit:
  %temp = call i64 @weave_emit_next_temp(ptr %ctx)
  %s0 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.tmp_prefix)
  %temp_i32 = trunc i64 %temp to i32
  %s1 = call i32 @weave_emit_i32(ptr %ctx, i32 %temp_i32)

  %op = trunc i64 %op_wide to i32
  %op_text_status = call i32 @weave_emit_binary_op_text(ptr %ctx, i32 %op)

  %s2 = call i32 @weave_emit_expr_operand(ptr %ctx, i64 %lhs_node)

  %is_cmp_op = icmp sge i32 %op, 5
  br i1 %is_cmp_op, label %emit_cmp_rhs, label %emit_i32_rhs

emit_i32_rhs:
  %s3 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.comma_i32)
  %s4 = call i32 @weave_emit_expr_operand(ptr %ctx, i64 %rhs_node)
  %s5 = call i32 @weave_emit_newline(ptr %ctx)
  %s3_failed = icmp ne i32 %s3, 0
  %s4_failed = icmp ne i32 %s4, 0
  %s5_failed = icmp ne i32 %s5, 0
  %i32_tail_bad0 = or i1 %s3_failed, %s4_failed
  %i32_tail_bad = or i1 %i32_tail_bad0, %s5_failed
  br label %check_status

emit_cmp_rhs:
  %s6 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.comma_i32)
  %s7 = call i32 @weave_emit_expr_operand(ptr %ctx, i64 %rhs_node)
  %s8 = call i32 @weave_emit_newline(ptr %ctx)
  %s6_failed = icmp ne i32 %s6, 0
  %s7_failed = icmp ne i32 %s7, 0
  %s8_failed = icmp ne i32 %s8, 0
  %cmp_tail_bad0 = or i1 %s6_failed, %s7_failed
  %cmp_tail_bad = or i1 %cmp_tail_bad0, %s8_failed
  br label %check_status

check_status:
  %tail_bad = phi i1 [%i32_tail_bad, %emit_i32_rhs], [%cmp_tail_bad, %emit_cmp_rhs]
  %head_s0_failed = icmp ne i32 %s0, 0
  %head_s1_failed = icmp ne i32 %s1, 0
  %op_text_failed = icmp ne i32 %op_text_status, 0
  %s2_failed = icmp ne i32 %s2, 0
  %head_bad1 = or i1 %head_s0_failed, %head_s1_failed
  %head_bad2 = or i1 %op_text_failed, %s2_failed
  %head_bad = or i1 %head_bad1, %head_bad2
  %bad = or i1 %head_bad, %tail_bad
  br i1 %bad, label %fail, label %success

success:
  ret i64 %temp

fail:
  ret i64 -9223372036854775808
}

; ----------------------------------------------------------------------------
; weave_emit_binary_op_text
; ----------------------------------------------------------------------------

define i32 @weave_emit_binary_op_text(ptr %ctx, i32 %op) {
entry:
  %is_add = icmp eq i32 %op, 1
  br i1 %is_add, label %add, label %check_sub

check_sub:
  %is_sub = icmp eq i32 %op, 2
  br i1 %is_sub, label %sub, label %check_mul

check_mul:
  %is_mul = icmp eq i32 %op, 3
  br i1 %is_mul, label %mul, label %check_div

check_div:
  %is_div = icmp eq i32 %op, 4
  br i1 %is_div, label %div, label %check_eq

check_eq:
  %is_eq = icmp eq i32 %op, 5
  br i1 %is_eq, label %eq, label %check_ne

check_ne:
  %is_ne = icmp eq i32 %op, 6
  br i1 %is_ne, label %ne, label %check_lt

check_lt:
  %is_lt = icmp eq i32 %op, 7
  br i1 %is_lt, label %lt, label %check_le

check_le:
  %is_le = icmp eq i32 %op, 8
  br i1 %is_le, label %le, label %check_gt

check_gt:
  %is_gt = icmp eq i32 %op, 9
  br i1 %is_gt, label %gt, label %check_ge

check_ge:
  %is_ge = icmp eq i32 %op, 10
  br i1 %is_ge, label %ge, label %fail

add:
  %s_add = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.add)
  ret i32 %s_add

sub:
  %s_sub = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.sub)
  ret i32 %s_sub

mul:
  %s_mul = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.mul)
  ret i32 %s_mul

div:
  %s_div = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.div)
  ret i32 %s_div

eq:
  %s_eq = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.icmp_eq)
  ret i32 %s_eq

ne:
  %s_ne = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.icmp_ne)
  ret i32 %s_ne

lt:
  %s_lt = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.icmp_lt)
  ret i32 %s_lt

le:
  %s_le = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.icmp_le)
  ret i32 %s_le

gt:
  %s_gt = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.icmp_gt)
  ret i32 %s_gt

ge:
  %s_ge = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.icmp_ge)
  ret i32 %s_ge

fail:
  ret i32 1
}

; ----------------------------------------------------------------------------
; weave_emit_expr
; ----------------------------------------------------------------------------
;
; Returns emitted-value descriptor or INT64_MIN on failure.


define i64 @weave_emit_expr(ptr %ctx, i64 %node_index) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %kind = call i32 @weave_ast_kind(ptr %ast, i64 %node_index)

  %is_int = icmp eq i32 %kind, 11
  br i1 %is_int, label %integer, label %check_binary

check_binary:
  %is_binary = icmp eq i32 %kind, 10
  br i1 %is_binary, label %binary, label %check_call

check_call:
  %is_call = icmp eq i32 %kind, 9
  br i1 %is_call, label %call, label %unsupported

integer:
  %value_wide = call i64 @weave_ast_a(ptr %ast, i64 %node_index)
  %value = trunc i64 %value_wide to i32
  %encoded = call i64 @weave_emit_immediate_value(i32 %value)
  ret i64 %encoded

binary:
  %binary_value = call i64 @weave_emit_binary_expr(ptr %ctx, i64 %node_index)
  ret i64 %binary_value

call:
  %call_value = call i64 @weave_emit_call_expr(ptr %ctx, i64 %node_index)
  ret i64 %call_value

unsupported:
  ret i64 -9223372036854775808
}

; ----------------------------------------------------------------------------
; weave_emit_call_expr
; ----------------------------------------------------------------------------
;
; Stage 0 supports only one i32 argument.


define i64 @weave_emit_call_expr(ptr %ctx, i64 %node_index) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %arg_node = call i64 @weave_ast_a(ptr %ast, i64 %node_index)
  %name_start = call i64 @weave_ast_text_start(ptr %ast, i64 %node_index)
  %name_len = call i64 @weave_ast_text_len(ptr %ast, i64 %node_index)

  %arg_value = call i64 @weave_emit_expr(ptr %ctx, i64 %arg_node)
  %arg_kind = call i32 @weave_ast_kind(ptr %ast, i64 %arg_node)
  %arg_is_name = icmp eq i32 %arg_kind, 13
  br i1 %arg_is_name, label %emit, label %check_arg

check_arg:
  %arg_failed = icmp eq i64 %arg_value, -9223372036854775808
  br i1 %arg_failed, label %fail, label %emit

emit:
  %temp = call i64 @weave_emit_next_temp(ptr %ctx)
  %s0 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.tmp_prefix)
  %temp_i32 = trunc i64 %temp to i32
  %s1 = call i32 @weave_emit_i32(ptr %ctx, i32 %temp_i32)
  %s2 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.call_i32)
  %s3 = call i32 @weave_emit_source_slice(ptr %ctx, i64 %name_start, i64 %name_len)
  %s4 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.call_sig_1)
  %s5 = call i32 @weave_emit_expr_operand(ptr %ctx, i64 %arg_node)
  %s6 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.call_sig_end)

  %s0_failed = icmp ne i32 %s0, 0
  %s1_failed = icmp ne i32 %s1, 0
  %s2_failed = icmp ne i32 %s2, 0
  %s3_failed = icmp ne i32 %s3, 0
  %s4_failed = icmp ne i32 %s4, 0
  %s5_failed = icmp ne i32 %s5, 0
  %b0 = or i1 %s0_failed, %s1_failed
  %b1 = or i1 %s2_failed, %s3_failed
  %b2 = or i1 %s4_failed, %s5_failed
  %b3 = icmp ne i32 %s6, 0
  %bad01 = or i1 %b0, %b1
  %bad23 = or i1 %b2, %b3
  %bad = or i1 %bad01, %bad23
  br i1 %bad, label %fail, label %success

success:
  ret i64 %temp

fail:
  ret i64 -9223372036854775808
}

; ----------------------------------------------------------------------------
; weave_emit_return_stmt
; ----------------------------------------------------------------------------

define i32 @weave_emit_return_stmt(ptr %ctx, i64 %node_index) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %expr_node = call i64 @weave_ast_a(ptr %ast, i64 %node_index)
  %expr_kind = call i32 @weave_ast_kind(ptr %ast, i64 %expr_node)
  %expr_is_name = icmp eq i32 %expr_kind, 13
  br i1 %expr_is_name, label %emit, label %emit_value

emit_value:
  %value = call i64 @weave_emit_expr(ptr %ctx, i64 %expr_node)
  %failed = icmp eq i64 %value, -9223372036854775808
  br i1 %failed, label %fail, label %emit

emit:
  %value_for_ret = phi i64 [0, %entry], [%value, %emit_value]
  %s0 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.ret_i32)
  br i1 %expr_is_name, label %emit_name_operand, label %emit_value_operand

emit_name_operand:
  %s1_name = call i32 @weave_emit_expr_operand(ptr %ctx, i64 %expr_node)
  br label %finish_ret

emit_value_operand:
  %s1_value = call i32 @weave_emit_operand(ptr %ctx, i64 %value_for_ret)
  br label %finish_ret

finish_ret:
  %s1 = phi i32 [%s1_name, %emit_name_operand], [%s1_value, %emit_value_operand]
  %s2 = call i32 @weave_emit_newline(ptr %ctx)
  %s0_failed = icmp ne i32 %s0, 0
  %s1_failed = icmp ne i32 %s1, 0
  %s2_failed = icmp ne i32 %s2, 0
  %bad01 = or i1 %s0_failed, %s1_failed
  %bad = or i1 %bad01, %s2_failed
  br i1 %bad, label %fail, label %success

success:
  ret i32 0

fail:
  ret i32 1
}

; ----------------------------------------------------------------------------
; weave_emit_let_stmt
; ----------------------------------------------------------------------------

define i32 @weave_emit_let_stmt(ptr %ctx, i64 %node_index) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %expr_node = call i64 @weave_ast_a(ptr %ast, i64 %node_index)
  %name_start = call i64 @weave_ast_text_start(ptr %ast, i64 %node_index)
  %name_len = call i64 @weave_ast_text_len(ptr %ast, i64 %node_index)

  %expr_kind = call i32 @weave_ast_kind(ptr %ast, i64 %expr_node)
  %expr_is_name = icmp eq i32 %expr_kind, 13
  br i1 %expr_is_name, label %emit_assignment, label %emit_value

emit_value:
  %value = call i64 @weave_emit_expr(ptr %ctx, i64 %expr_node)
  %failed = icmp eq i64 %value, -9223372036854775808
  br i1 %failed, label %fail, label %emit_assignment

emit_assignment:
  %value_for_let = phi i64 [0, %entry], [%value, %emit_value]
  %s0 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.percent)
  %s1 = call i32 @weave_emit_source_slice(ptr %ctx, i64 %name_start, i64 %name_len)
  %s2 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.eq)
  %s3 = call i32 @weave_emit_i32(ptr %ctx, i32 0)
  %s4 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.comma_i32)
  br i1 %expr_is_name, label %emit_name_operand, label %emit_value_operand

emit_name_operand:
  %s5_name = call i32 @weave_emit_expr_operand(ptr %ctx, i64 %expr_node)
  br label %finish

emit_value_operand:
  %s5_value = call i32 @weave_emit_operand(ptr %ctx, i64 %value_for_let)
  br label %finish

finish:
  %s5 = phi i32 [%s5_name, %emit_name_operand], [%s5_value, %emit_value_operand]
  %s6 = call i32 @weave_emit_newline(ptr %ctx)
  %s0_failed = icmp ne i32 %s0, 0
  %s1_failed = icmp ne i32 %s1, 0
  %s2_failed = icmp ne i32 %s2, 0
  %s3_failed = icmp ne i32 %s3, 0
  %s4_failed = icmp ne i32 %s4, 0
  %s5_failed = icmp ne i32 %s5, 0
  %s6_failed = icmp ne i32 %s6, 0
  %bad01 = or i1 %s0_failed, %s1_failed
  %bad23 = or i1 %s2_failed, %s3_failed
  %bad45 = or i1 %s4_failed, %s5_failed
  %bad0123 = or i1 %bad01, %bad23
  %bad012345 = or i1 %bad0123, %bad45
  %bad = or i1 %bad012345, %s6_failed
  br i1 %bad, label %fail, label %success

success:
  ret i32 0

fail:
  ret i32 1
}

; ----------------------------------------------------------------------------
; weave_emit_block
; ----------------------------------------------------------------------------

define i32 @weave_emit_block(ptr %ctx, i64 %node_index) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %first = call i64 @weave_ast_a(ptr %ast, i64 %node_index)
  %last = call i64 @weave_ast_b(ptr %ast, i64 %node_index)
  br label %loop

loop:
  %i = phi i64 [%first, %entry], [%next_i, %after_node]
  %done = icmp sgt i64 %i, %last
  br i1 %done, label %success, label %check_node

check_node:
  %kind = call i32 @weave_ast_kind(ptr %ast, i64 %i)
  %is_block = icmp eq i32 %kind, 3
  br i1 %is_block, label %emit_node, label %check_return

check_return:
  %is_return = icmp eq i32 %kind, 4
  br i1 %is_return, label %emit_node, label %check_let

check_let:
  %is_let = icmp eq i32 %kind, 7
  br i1 %is_let, label %emit_node, label %after_node

emit_node:
  %status = call i32 @weave_emit_stmt(ptr %ctx, i64 %i)
  %failed = icmp ne i32 %status, 0
  br i1 %failed, label %fail, label %after_node

after_node:
  %next_i = add i64 %i, 1
  br label %loop

success:
  ret i32 0

fail:
  ret i32 1
}

; ----------------------------------------------------------------------------
; weave_emit_stmt
; ----------------------------------------------------------------------------
;
; Stage 0 emits blocks, let statements, return statements, and expression
; statements. More statement kinds are admitted one ladder test at a time.


define i32 @weave_emit_stmt(ptr %ctx, i64 %node_index) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %kind = call i32 @weave_ast_kind(ptr %ast, i64 %node_index)

  %is_block = icmp eq i32 %kind, 3
  br i1 %is_block, label %block_stmt, label %check_return

check_return:
  %is_return = icmp eq i32 %kind, 4
  br i1 %is_return, label %return_stmt, label %check_let

check_let:
  %is_let = icmp eq i32 %kind, 7
  br i1 %is_let, label %let_stmt, label %expr_stmt

block_stmt:
  %block_status = call i32 @weave_emit_block(ptr %ctx, i64 %node_index)
  ret i32 %block_status

return_stmt:
  %status = call i32 @weave_emit_return_stmt(ptr %ctx, i64 %node_index)
  ret i32 %status

let_stmt:
  %let_status = call i32 @weave_emit_let_stmt(ptr %ctx, i64 %node_index)
  ret i32 %let_status

expr_stmt:
  %value = call i64 @weave_emit_expr(ptr %ctx, i64 %node_index)
  %failed = icmp eq i64 %value, -9223372036854775808
  br i1 %failed, label %fail, label %success

success:
  ret i32 0

fail:
  ret i32 1
}

; ----------------------------------------------------------------------------
; weave_emit_function
; ----------------------------------------------------------------------------

define i32 @weave_emit_function(ptr %ctx, i64 %node_index) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %body_node = call i64 @weave_ast_a(ptr %ast, i64 %node_index)
  %param_start = call i64 @weave_ast_b(ptr %ast, i64 %node_index)
  %param_len = call i64 @weave_ast_c(ptr %ast, i64 %node_index)
  %name_start = call i64 @weave_ast_text_start(ptr %ast, i64 %node_index)
  %name_len = call i64 @weave_ast_text_len(ptr %ast, i64 %node_index)

  %s0 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.define_i32)
  %s1 = call i32 @weave_emit_source_slice(ptr %ctx, i64 %name_start, i64 %name_len)
  %has_param = icmp ne i64 %param_len, 0
  br i1 %has_param, label %emit_param_sig, label %emit_no_param_sig

emit_no_param_sig:
  %s2_no_param = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.fn_sig)
  br label %emit_entry

emit_param_sig:
  %s2_param_a = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.fn_sig_1_prefix)
  %s2_param_b = call i32 @weave_emit_source_slice(ptr %ctx, i64 %param_start, i64 %param_len)
  %s2_param_c = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.fn_sig_1_suffix)
  %s2_param_a_failed = icmp ne i32 %s2_param_a, 0
  %s2_param_b_failed = icmp ne i32 %s2_param_b, 0
  %s2_param_c_failed = icmp ne i32 %s2_param_c, 0
  %s2_param_bad0 = or i1 %s2_param_a_failed, %s2_param_b_failed
  %s2_param_bad = or i1 %s2_param_bad0, %s2_param_c_failed
  br label %emit_entry

emit_entry:
  %s2 = phi i32 [%s2_no_param, %emit_no_param_sig], [0, %emit_param_sig]
  %s2_param_failed = phi i1 [false, %emit_no_param_sig], [%s2_param_bad, %emit_param_sig]
  %s3 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.entry)

  %s0_failed = icmp ne i32 %s0, 0
  %s1_failed = icmp ne i32 %s1, 0
  %s2_failed = icmp ne i32 %s2, 0
  %s3_failed = icmp ne i32 %s3, 0
  %head_bad0 = or i1 %s0_failed, %s1_failed
  %head_bad1 = or i1 %s2_failed, %s3_failed
  %head_bad2 = or i1 %head_bad1, %s2_param_failed
  %head_bad = or i1 %head_bad0, %head_bad2
  br i1 %head_bad, label %fail, label %body

body:
  %body_status = call i32 @weave_emit_stmt(ptr %ctx, i64 %body_node)
  %body_failed = icmp ne i32 %body_status, 0
  br i1 %body_failed, label %fail, label %close

close:
  %s4 = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.close_fn)
  %close_failed = icmp ne i32 %s4, 0
  br i1 %close_failed, label %fail, label %success

success:
  ret i32 0

fail:
  ret i32 1
}

; ----------------------------------------------------------------------------
; weave_emit_program
; ----------------------------------------------------------------------------
;
; Stage 0 scans the compact AST and emits nodes whose kind is AST_FUNCTION.
; Function nodes are not contiguous because each function body is parsed before
; the function wrapper node is appended.


define i32 @weave_emit_program(ptr %ctx, i64 %program_node) {
entry:
  %ast = call ptr @weave_emit_ast(ptr %ctx)
  %node_count = call i64 @weave_ast_count(ptr %ast)

  %header_status = call i32 @weave_emit_cstr(ptr %ctx, ptr @weave.emit.module_header)
  %header_failed = icmp ne i32 %header_status, 0
  br i1 %header_failed, label %fail, label %loop

loop:
  %i = phi i64 [0, %entry], [%next_i, %after_node]
  %done = icmp uge i64 %i, %node_count
  br i1 %done, label %success, label %check_node

check_node:
  %kind = call i32 @weave_ast_kind(ptr %ast, i64 %i)
  %is_function = icmp eq i32 %kind, 2
  br i1 %is_function, label %emit_function, label %after_node

emit_function:
  %status = call i32 @weave_emit_function(ptr %ctx, i64 %i)
  %failed = icmp ne i32 %status, 0
  br i1 %failed, label %fail, label %after_node

after_node:
  %next_i = add i64 %i, 1
  br label %loop

success:
  ret i32 0

fail:
  ret i32 1
}

; ----------------------------------------------------------------------------
; weave_emit_llvm
;
; Public emitter entry point.
;
; Returns:
;   0 on success
;   1 on failure
; ----------------------------------------------------------------------------

define i32 @weave_emit_llvm(ptr %source, ptr %ast, i64 %program_node, ptr %out) {
entry:
  %ctx_storage = alloca %weave.EmitContext
  call void @weave_emit_context_init(ptr %ctx_storage, ptr %source, ptr %ast, ptr %out)
  %status = call i32 @weave_emit_program(ptr %ctx_storage, i64 %program_node)
  ret i32 %status
}
